### ISSUE TITLE
Develop mock implementation and write evaluation report for Misago

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#100]
This issue centers on developing a mock implementation and an evaluation report for the Misago forum framework for our board games website. The mockup will help the team visualize potential forum layouts, navigation, and interactive elements utilizing the Misago framework. This will provide the team with a solid understanding of the positives and negatives of implementing a Misago framework.

**Comment by joshuamonroe** [comment]
To better break down the work necessary to develop the mock implementation, two additional issues have been opened. These issues should be completed before writing the report for Misago.
- #146 
- #150

**Comment by bburgess19** [comment]
# Report
This comment will present our analysis of Misago

## Background
Misago is a standalone forum solution which is **intended to be used with minimal setup/configuration**. It comes with pre-built functionality and well-developed frontend. Some of the features include:
1. Markup language posts
2. Unlimited depths threads
3. Private threads

You can read more about their features [here](https://github.com/rafalp/Misago#production-use). The specific use case is geared for applications which need a plug-and-play solution with minimal anticipated extendibility.

## Setup
In our tests, we used [Docker](https://docs.docker.com/engine/install/) to install Misago. You can read more about our installation details [here](https://github.com/uchicago-cs/chigame/blob/9be728cff6abc80da32dd61a0af99594980eb7fd/src/sandbox/misago-demo/MISAGO.md?plain=1#L8). Crucially, Misago cannot be pip-installed and ran as part as the larger project -- it must run an a containerized Docker instance. 

## Result

 1. This is the initial interface of the forums app with all of the listed threads created from users. 
<img width="1273" alt="Screenshot 2023-11-15 at 4 25 02 PM" src="https://github.com/uchicago-cs/chigame/assets/121977204/f3b0eebc-ccf2-4371-a806-e9d0b8ebaedc">

 2. When clicking on "Register", you are directed to the "Register" page with the input fields shown below using email authentication. 
<img width="599" alt="Screenshot 2023-11-15 at 4 25 13 PM" src="https://github.com/uchicago-cs/chigame/assets/121977204/05c9fc19-b6ff-4a0b-98b1-f10745fba383">

  3. Once registered and logged in, you can create a new thread with the input fields shown below. 
<img width="1256" alt="Screenshot 2023-11-15 at 4 28 11 PM" src="https://github.com/uchicago-cs/chigame/assets/121977204/85cf0c11-e676-42ac-9b74-e6b16bb34adf">
 
  4. Upon clicking on the new thread, you are navigated to the following singular thread interface.  From this, you can "Edit" the thread as well, and so forth. 
<img width="1223" alt="Screenshot 2023-11-15 at 4 28 36 PM" src="https://github.com/uchicago-cs/chigame/assets/121977204/60de7eb1-2a59-4c41-99f9-3a6dd5a0f013">
  
  


## Extensibility
Despite being programmed in Django, Misago is intended as a standalone, plug-in-play product, it doesn't offer anything in the way of extendibility. Extendibility would largely mean trimming features off of their implementation and building in infrastructure to allow greater extendibility.

## Responsibility
@giomhern setup a demo instance of Misago, trying out their purported features.
@joshuamonroe created issues to facilitate clear communications throughout.
@bburgess19 refined the documentation file for this process, and reorganized the file infrastructure for this test.

**Comment by giomhern** [comment]
I have added the comments on the result. Let me know if I should add any specific options. I kept it generally brief considering there are a number of additional features such as polls which I do not know if they are remotely applicable.

**Comment by bburgess19** [comment]
Awesome, like the images and the descriptions. Closing.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work y'all! Appreciate the well done markdown formatting and report writing! 

With this report it becomes very clear that Misago is not the option we would've wanted to go with for Chigame.

Thank you for your work and keep moving forward!
