### ISSUE TITLE
Work with matches to have attribute determining if match is part of tournament

### ISSUE THREAD

**Issue by rqueiroz20** [uchicago-cs/chigame#104]
This task involves communicating with the Matches team to determine how to differentiate a match in a tournament versus a match outside of one. Some aspects that could uniquely define a tournament match could be a win condition and a live chat that is recorded after the game is concluded.

**Comment by rqueiroz20** [comment]
Communication with the Matches team went well. They left their comments regarding how they're implementing matches in [this Wiki link](https://github.com/uchicago-cs/chigame/wiki/Matches-~-Tournament-Integration). In short, they view our current ERD as a "super-lobby" in which several Lobby entities are initialized when a Tournament object is initialized. They suggest that "In this way, we can create an easy integration of the matches and tournaments functionality: just plug matches in, through the creation of this lobby." So I believe that is the approach we are going with, but if this turns out to be problematic in the future, we can always go back and change it. I'm closing this issue for now since both teams seem to agree on how that integration will occur, but if we need to revisit this thought process we can always reopen this issue.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Going to give this a minor rating, as most of the work was done from the matches front. Good work regardless documenting your progress on this issue!
