### ISSUE TITLE
(matches) data modeling for matches (Annika)

### ISSUE THREAD

**Issue by ambr-lise** [uchicago-cs/chigame#109]
Goal: We need a way of storing match outcome data, such as win records, point totals, and resources gained. This data will need to be referenced by future matches and by the users who have played in the match.

Deliverables: An ERD and tables for match outcome data, and documentation detailing why certain decisions were made and intended uses for the data structures.

**Comment by ambr-lise** [comment]
Made and linked a PR for the changes to games/models.py, which consist of small updates to Matches and Players. We have made the decision not to support legacy games (users who play legacy games on the site can still track meta-relevant information using pen and paper). Added an ERD reflecting these changes to the Wiki: https://github.com/uchicago-cs/chigame/wiki/Matches-~-ERD.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great job providing documentation on the data model. The addition of players was very smart and adds much more functionality for the future of matches.
