### ISSUE TITLE
Make non GET requests to Game CRUD pages available to staff users only

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#111]
We need to restrict non-GET requests to only be allowed from staff users. This means that the edit and create views should not be accessible to non-staff users. The links to the edit and create views should only be shown if the user is a staff member, and if a non-staff user goes to those URLs, it should return a HTTP 403 or 404 error

**Comment by ptlin25** [comment]
Created new branch `game-management/staff-access-only` for this issue

**Comment by ptlin25** [comment]
Code added to restrict access to non GET requests. Now, only staff can access edit and create views and urls. PR #117 for this issue

**Comment by ptlin25** [comment]
Added comments and resolved merge conflicts as requested by the review

**Comment by ptlin25** [comment]
This issue has been completed as of #117. The Game edit and create views can now only be accessed by staff members.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! Appreciate you adding update comments for things like creating branches and updates in related PR's!
