### ISSUE TITLE
Redesign and implement the lobby class according to user stories

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#113]
**Goal:** [Data Modeling for Lobby] Based on our user stories from Sprint 1, the current lobby table needs more attributes (or perhaps a different way of modeling). For example, user stories mention match start times as well as the modified game features. We need to redesign and implement the Lobby class to account for these additional features.

**Possible Deliverables:** 
- ERD
- Pull Request to implement new tables/classes
- Documentation detailing changes

**Comment by jiyeongchloe** [comment]
*in `matches/lobby-model` branch*
Confirmed @nugerhard 's updates to the Lobby model and added `game_modification_status` attribute for simple y/n type to help with advanced filtering

**Comment by jiyeongchloe** [comment]
When trying to merge (PR #140), `CI/ run-tests` is failing. I attempted to resolve this by pushing `migrations/0002_lobby.py`, but it didn't resolve it.

**Comment by jiyeongchloe** [comment]
Resolved the testing issue by specifying defaults for `match_status`, `game_mod_status`, and `time_constraint` and pushing an updated version of `migrations/0002_lobby.py`.
PR #140 should be good to go now; just waiting for reviews!

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR #140 has been merged and task is finished

**Nat:**
- Identified necessary attributes that needed to be added to lobby class
- Edited Lobby class in `models.py` to include `match_status`, `time_constraint`, and `lobby_created` attributes

**Chloe:**
- Added `game_mod_status` attribute to Lobby class in `models.py`
- Debugged PR test errors by making & committing migration and adding defaults to `match_status`, `time_constraint`, and `game_mod_status` attributes

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Similar comments to the ones left on your PR - good work! For sprint 3, it'd be nice to see simple documentation on the changes you guys made to the model.
