### ISSUE TITLE
Research django-filter

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#115]
**Goal:** The lobbies list page lists all lobbies with no specific organization. To make lobby searches more efficient, we want to implement advanced filtering capabilities where users can choose to display only lobbies with certain games, players, or match start times. We need to research how to add this.

**Possible Deliverables:**
- Wiki page

**Comment by nugerhard** [comment]
I have created a Django-filters quickstart page in the matches section of the wiki. You can find that [here](https://github.com/uchicago-cs/chigame/wiki/Matches-~-Quickstart-Guide-to-django-filters). I think Chloe will edit/revise as necessary, and then sign off.

**Comment by jiyeongchloe** [comment]
added sentences about order of filters, handling multiple filters, error handling, and clearing filters.

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
task is finished.

**Nat:**
- created the quickstart page with bulk of the information
    - Creating Filter Classes
    - Adding Filters to your View
    - Adding Filters to your HTML template
    
**Chloe:**
- revised the quickstart page to include bits of supplementary information
    - order of filters
    - handling multiple filters
    - error handling
    - clearing filters

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice work on this issue! Love the documentation as well, and I think it will be very helpful for other teams and not just matches.
