### ISSUE TITLE
Implementing profile path

### ISSUE THREAD

**Issue by AndrewM131** [uchicago-cs/chigame#119]

**Comment by AndrewM131** [comment]
Description: Create a path such that a user is able to access their personal information, and just their personal information. The path can be made in urls.py and links to a view of this information.

**Comment by AndrewM131** [comment]
Update: We met two times during the sprint, the second being November 12th, where we talked as a group on how to approach this issue as in the process of coding, we realized there were actually two sort of paths to a profile. Of these, one led to a view that allowed the user to change their name and update their email. Another led to a profile page that any user can access, and if the own user accesses this page, they can change their name, but if a separate user accesses this page, they can send a friend request. So what we decided to do is implement a link in the nav bar that links to a user's personal information or a personal "profile" and will display the user's personal information, and this way, a user can access their details without manually putting it in the URL.

**Comment by AndrewM131** [comment]
Update: First PR was made, it is awaiting review

**Comment by AndrewM131** [comment]
Update: Review comments were made, and are currently being addressed. They are mainly concerned with changing what is displayed and having a non-user not access this view.

**Comment by AndrewM131** [comment]
Update: the path will be accessed through the profile page and displays more private information about the user that accesses it. If a user is not of that page, they are given a message that they can't access the page. It will also not display password as it hasn't been implemented to properly reset a password unless on the admin view. It is also not available to see in the nav bar.

**Comment by AndrewM131** [comment]
Update: I removed the list of friends as that would be implemented in another PR, and I implemented the words "Admin of Chigame" if the user is an admin of chigame.

**Comment by AndrewM131** [comment]
Closing comment: At the start, the goal was to create a link in nav bar, and have personal information displayed that only the user of that information can access. That goal changed because it would be too confusing for a user to have a profile and account in the nav bar, so the link for account can be accessed through the user profile. I also added information in the account view page, such as name, a link to changing name, email, a link to changing email, bio, and it highlights if a user is an admin of chigame.
During the course of sprint 2 and 3, we met 3 times to discuss and code for the issue/PR, with myself commenting on the PR and issues, and any code updates were communicated over slack between the 3 of us.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work on this issue! It was really nice to be able to actually switch between the user and user profile page without needing to manually change the url. Docking a point for this issue spanning two sprints, but otherwise everything looks good.
