### ISSUE TITLE
Establish standardized terminology for forum user stories, ERD, etc.

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#123]
As @majorsylvie has noted in a [comment](https://github.com/uchicago-cs/chigame/issues/59#issuecomment-1790955358) on issue #59, it would be beneficial for us to standardize the terminology that we use to describe the forum across our user stories, the ERD, and other documentation. To this end, I propose that we use the following standardized terminology in our discussions and documentation of the forum. Please review and comment, be sure to point out anything that is unclear, or that could be added or improved. Once everyone has weighed in and we've incorporated any feedback, the intent is to publish these standards to the wiki for future reference and update any existing wiki content to align with them.

- **The Forum**
  - The chigame forum as a whole.
- **Category**
  - A collection of subforums., i.e. the Games or General category.
- **Subforum**
  - A collection of threads, i.e. the Game X subforum in the Games category or the Technical Help subforum in the General category.
  - Previously referred to as a **Community** in the ERD and a **Forum** elsewhere, these are also options worth considering, although I think **subforum** is probably the clearest.
- **Thread**
  - A collection of posts/comments, i.e. a user creates a thread to discuss the latest update to Game X in the Game X subforum.
  - Has also been referred to as a **discussion** or **discussion thread**.
- **Post**
  - An individual message within a thread, i.e. another user replies to the original post in a thread with a post of their own.
  - Has also been referred to as a **comment** or **reply**, which I think it’s still worth using these in user stories and conversation provided we make the following distinction and standardize on post at a technical level.
  - As an alternative, **comment** may be worth considering because **post** may have the potential to be confused with a POST request in the code.
- **Comment/Reply**
  - Same as post, but exclusive of the original post at the beginning of the thread.
- **Forum Admin**
  - An admin of the forum only (may also be chigame admin), this user has all of the permissions of a forum moderator, as well as the ability to add and delete categories and subforums. Preferably a staff member, although not necessarily a developer.
- **Forum Moderator**
  - A community member tasked with policing the forums. This user has permissions to do things like lock, delete, and pin posts; and ban or suspend users from the forum.

Some additional terms that are relevant but reside primarily outside of the scope of the forum itself:
- **Chigame Admin**
  - An admin of the chigame platform broadly, the highest permission level. Should be a staff member / developer.
- **Registered User** 
  - An authenticated user of the chigame platform broadly. Authentication and general account settings are managed outside of the forum but users may additionally have forum specific roles, permissions, statistics, and public profiles.
- **Unregistered User**
  - An unauthenticated user of the chigame platform broadly. Only has access to view public areas of the forum and cannot create threads or posts.
- **Group**
  - A group of users on the chigame platform broadly, these are managed outside of the forum but may have access to their own subforums and other forum functionality.
- **Group Admin**
  - A group owner, able to add or remove users from the group, modify group settings, schedule group events, etc.

**Comment by Benjoman12** [comment]
This is very thorough and looks good. After closing, we should add this page to the wiki and correct any existing user stories that use this terminology.

**Comment by bburgess19** [comment]
I concur, this is detailed, and I have no disagreements.

**Comment by giomhern** [comment]
This looks great! I will go ahead and also fix the user stories by removing the redundant definitions of the users considering we will add this in the wiki! 

Edit: Just did it right now! Everything is updated!

**Comment by joshuamonroe** [comment]
I've added a [Standard Terminology](https://github.com/uchicago-cs/chigame/wiki/Forums-~-Standard-Terminology) page to the wiki and updated the [ERD](https://github.com/uchicago-cs/chigame/wiki/Forums-~-Entity-Relationship-Diagram-(ERD)) to align with the new standards.

![Image](https://github.com/uchicago-cs/chigame/assets/59244307/d00e9d04-5c84-4279-8147-008ecb5bbad1)

Thanks to @giomhern  for reviewing and updating the user stories, and to @Benjoman12 and @bburgess19 for reviewing. Closing this issue now.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Excellent job! This is exactly what I was hoping for when I asked for standardized terminology.
Great job acting on feedback, making a detailed issue, having everyone make comments and express their approval in writing via updates, as well as a clear closing statement @'ing the relevant people and stating the developer contributions.

This is exactly the way a good documentation related issue should go, and the work you've done now will set up you (and generations after you) for hopefully many less headaches than they otherwise would have.

Great work and keep moving forward!
