### ISSUE TITLE
Notifications: create inbox

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#124]
Create an inbox that contains all new updates such as new friend requests. It should show unread notifications from most recent to least recent. Users should have the ability to delete notification from their inbox. Clicking on an update should redirect to a page about this notification depending on what type of notification it is. For example, if it is a friend invitation, it should direct to a the profile of sender. The profile page should have a button to accept or reject the invitations which is handled in #125 . Refreshing a profile page should show new incoming notifications if there is any. We might want to display notifications in real time in the future.

**Comment by omarelkashef** [comment]
We realized we need a model for notification that the inbox will query. We created another issue #127

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Very clear summary of the intended goals for this issue like the exact actions a user can take. Lacking a closing statement, but otherwise nice job!
