### ISSUE TITLE
Adding directing from friend requests in inbox to profile page and add option to read and delete notifications

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#125]
Clicking on a Friend Invitation in the inbox should direct to the sender profile page and that page should display options to accept or reject friendship. This builds on the implementing an inbox in #124. There should be buttons to read, unread and delete notifications and that should make them look different in the inbox.

**Comment by omarelkashef** [comment]
While working on redirection from friend requests, we added some bootstrap and JS to the inbox page. Also, we create another issue to add the option to select multiple notifications to do some action (e.g. deleting). we are trying to decide whether that is better done through view function or an API POST request.

**Comment by omarelkashef** [comment]
The redirection work as well as the default message was done based on Notification that belong to FriendInvitations. Other types of Notifications can be implemented once we discuss with respective team what the behavior of clocking on a their Notification should be.

**Comment by omarelkashef** [comment]
Closing Statement: We handled clicks on Notification of type FriendInvitation where they redirect to the sender's profile page. We also added buttons to read, unread and delete notifications in the inbox page as well as default message for friend request notifications.
@omarelkashef worked on the backend logic and view functions
@24raniwalar worked on the front end html, bootstrap and JS

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice usage of the notification model and also well written updates as the issue progressed. This issue spanned two sprints but looks good otherwise.
