### ISSUE TITLE
Create Tables.md file for tournaments data model.

### ISSUE THREAD

**Issue by Riyush** [uchicago-cs/chigame#126]
This task requires converting our existing ERD model into a Tables.MD file. After we confirm our model with the users and matches group, we have a fully integrated ERD that can be turned into a Tables.md file. The Tables.md will specify all the attributes of each model in our ERD as well as the nature of the relationships between our models. The Tables.md file can then be converted into a models.py file after verifying its accuracy in this issue.

**Comment by Riyush** [comment]
I have created a sample tables.md file to represent all the models and relationships in our ERD. I didn't put the file in the repository since the tables.md file will likely end up in the wiki. Instead I put it all on this Word Document: https://docs.google.com/document/d/1X7E15ftmn8C1u5wREQtW1C-Xrp-Lox90shosamF-vgQ/edit?usp=sharing
Feel free to check out the file and modify it as needed. Also you can paste it into a vscode Tables.md file for better readability. I tried to follow the ERD Diagram on this page: https://github.com/uchicago-cs/chigame/wiki/Tournament-~-Entity-Relationship-Diagram

**Comment by MuyanXie** [comment]
Bumping into this again. Looks like we may want to update the Tables.md file to reflect changes in the Announcement Model and the add of the token attribute in Users. @Riyush could you please look into this? Other than that, it looks awesome to me

**Comment by Riyush** [comment]
I think that change can be a seperate issue if needed. It is satisfactory as of now.

**Comment by Riyush** [comment]
The Tables.md file has been completed. It includes information on all the attributes and relationships for a tournament model including other models like User and Match. This information was also used to create the ERD file.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice work creating the table.md file. However, google docs should not be used in this class, and everything should be placed in the Wiki instead. Summary and updates are well written.
