### ISSUE TITLE
Implement django-tables2 in lobby list view

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#128]
**Goal:** We currently only list the available lobbies in bullet points. To enhance use experience and to be able to implement filtering capabilities in the future, we want to implement `django-tables2` to create nicer tables in the lobby list view.

**Deliverables:**
- PR that creates `tables.py` and makes appropriate changes to the `views.py` classes and respective HTML files

**Comment by jiyeongchloe** [comment]
created `matches/lobby-django-tables` branch

**Comment by jiyeongchloe** [comment]
To implement django-tables2 to lobby list view, I

- added `django_tables2` to `requirements/base.txt`
- changed the lobby-list definitions and classes in `urls.py` and `views.py`
- added `tables.py`
- modified `lobby-list.html` to render the table instead of listing the lobbies in bullets

**Comment by jiyeongchloe** [comment]
made PR #158 but running into `flake8` issues in CI

**Comment by jiyeongchloe** [comment]
`flake8` issue in CI is now fixed and PR #158 just needs to be reviewed

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
task is finished with PR #158 being merged.

Chloe:
- added tables.py
- modified lobby-list.html
- changed definitions and classes in urls.py and views.py

Lucien:
- helped figure out changes to requirements
- help fix CI issues

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great work on the implementation of this view - it made the lobbies list view much more presentable and easy to read. Also, nice job with the updates and clear outline of deliverables for this issue.
