### ISSUE TITLE
Update Game views to account for newly added attributes and respect new lines

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#131]
With issue #92 updating the Game model, the Game views will need to be updated to reflect the newly added attributes. In particular, `game_detail.html` needs to be updated to should show all of the Game attributes. New fields need to be added to the game edit and create views for the new attributes.

**Comment by willcravitz** [comment]
As @majorsylvie pointed out, our detail page currently does not respect new lines:

![Image](https://github.com/uchicago-cs/chigame/assets/93291811/6bf5095d-5f01-431d-8983-c020f9ce1fc0)
![Image](https://github.com/uchicago-cs/chigame/assets/93291811/d3ffca77-9222-4a15-9b46-f557e0d7b09c)

We'll address this in this issue.

**Comment by ptlin25** [comment]
Created branch `game-management/update-game-crud` for this issue

**Comment by ptlin25** [comment]
The create and edit views have been updated to `fields = '__all__'`, so all fields/attributes are now shown. Added |linebreaksbr (documentation [here ](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#linebreaksbr)) to the game detail page, so that line breaks now show up correctly

**Comment by willcravitz** [comment]
Thanks @ptlin25. Before you close this out I'm going to update the detail page to display all the new attributes.

**Comment by willcravitz** [comment]
Just updated the game detail page and pushed to the `game-management/update-game-crud` branch. Here's an example of what it looks like for Catan:
<img width="400" alt="image" src="https://github.com/uchicago-cs/chigame/assets/93291811/a706b67c-847d-4dd6-9deb-96549ac3ddcb">
I think we're ready to open a PR for this issue.

**Comment by ptlin25** [comment]
This issue has been completed via #192. The game detail view was updated by @willcravitz to include the new attributes that were added and to properly display line breaks in the description field. @ptlin25 created a new GameForm to display all of the required fields in the game edit and create views as well as to add more context to the form fields.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job y'all!
Good job providing images and referencing feedback relevant to this issue (such as my PR comments!)

I appreciate the use of markdown formatting for code in your update comments! Makes them even more readable
