### ISSUE TITLE
Add a wiki page to document how the game name autocompletion code works

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#134]
The current code used to implement autocompletion for game names is quite confusing and involves libraries that are not taught in CS220. To help future teams that will need to use the autocompletion feature, we will add a new page to the wiki to explain how the code works and how the autocompletion feature as a whole works. 
Edited by Patrick Lin (ptlin25)

**Comment by ptlin25** [comment]
A wiki page explaining how the game name autocompletion code works has been added to the chigame wiki, so this issue is completed. The wiki page can be found [here](https://github.com/uchicago-cs/chigame/wiki/Games-~-Game-Name-Autocompletion).

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Would've done good with more updates through the span of the work! 

Beyond that, thank you for your work and posting this to the wiki! This is great documentation.
