### ISSUE TITLE
(user profiles) friending: accept/decline functionality

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#139]
We need to display "Accept" and "Decline" options for users when visiting profile pages that send them a friend invitation.  Trying to accept/decline an invitation that does not exist or where you are not the receiver should redirect you back to your profile page with a proper error message. Accepting an invitation adds user2 to user1 friends list and adds user1 to users2 friends list while declining an invitation deletes that instance of FriendInvitation.

**Comment by omarelkashef** [comment]
We need to display "Accept" and "Decline" options for users when visiting profile pages that send them a friend invitation. There is currently an endpoint to accept FriendInvitation if you know the ID of the sender so we need to expand this functionality to allow for declining invitations as well.

**Comment by omarelkashef** [comment]
We also need to prevent user from sending friend invitations to users that have already send them friend invitations.

**Comment by omarelkashef** [comment]
@elizabethli31 digging deeper into the friends functionality, I think it would make a lot of thing easier if we we make friends a relationship between two instances of UserProfile instead of a UserProfile and User. The latter implementation complicated the logic of keeping track, adding, removing and updating friends. Since User and UserProfile is one-to-one, this proposed change does not seem to pose any problems. It would also make sense to have it as a relationship between User and User but if we want to separate User and UserProfile to support API users, UserProfile would be the go to.

**Comment by omarelkashef** [comment]
The functions that handle accepting and declining invitation take a FriendInvitation.pk as a parameter which means that they will only delete that particular invitation even if there exists other friend invitations between the sender and receiver.

**Comment by omarelkashef** [comment]
Closing statement:
This addresses the functionality of friend request buttons within profile views. When visiting profile pages that have sent a friend invitation, the page now appropriately displays options to accept or decline the invitation. If the users are already friends, the option to remove the friend is shown. Additionally, if a friend invitation had been sent previously, the page now provides the option to cancel the friend request. In case a user attempts to accept or decline an invitation that does not exist or where they are not the intended recipient, they will be redirected back to their profile page with a relevant error message. Upon accepting an invitation, the users become friends, and declining results in the removal of the invitation. It's worth noting that the functionality of the "remove friend" button is pending redirection and will be addressed in a separate issue.

@24raniwalar worked on designing the new required endpoints
@omarelkashef worked on the logic of the friending feature

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice description of the exact goals for this issue along with a closing statement that precisely explained the implemented actions. I also agree with the comment on UserProfile / User friending relationship and think it should be addressed next year.
