### ISSUE TITLE
Direct users who are not logged-in to the Log-in page when clicking on the join lobby button

### ISSUE THREAD

**Issue by xylucien** [uchicago-cs/chigame#141]
as title. Users who are not logged in should be able to view the lobby detail, but not to join the lobby.

**Comment by xylucien** [comment]
At first, I did the check by retrieving the user authorization status from the request, but it occurs that there's a more elegant way, which is done by adding a @login_required decorator before the join-lobby method.

**Comment by xylucien** [comment]
Closing statement: this is s rather quick change and the functionality works fine. 

Lucien: implemented a more redundant version first but was later replaced by Moses' implementation
Moses: came up with the @login_required decorator idea!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great functionality for this issue. Title is very explanatory, but the summary description is too terse and should explain the exact deliverables for the issue.
