### ISSUE TITLE
Create Documentation/Strategy around Matches-Tournaments Integration

### ISSUE THREAD

**Issue by nugerhard** [uchicago-cs/chigame#142]
Create a wiki page containing feedback on the Tournament ERD, [here](https://github.com/uchicago-cs/chigame/wiki/Tournament-~-Entity-Relationship-Diagram). This documentation should evaluate design decisions by the Tournament team in light of the current design of lobbies and matches.

**Comment by nugerhard** [comment]
[Here](https://github.com/uchicago-cs/chigame/wiki/Matches-~-Tournament-Integration) is the wiki page. Once we get some feedback from the tournaments team, and that feedback is integrated, we will call this issue closed.

**Comment by nugerhard** [comment]
Closing Statement: The Tournaments group has said that they have looked at the document, and that it has made sense. As such, I will close this issue, and any future updates to integration documentation will be in a new issue.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work! Very clear documentation on the matches models. Next time make sure you add the x/matches label to this issue.
