### ISSUE TITLE
Add historical information view to display user's stats

### ISSUE THREAD

**Issue by AndrewM131** [uchicago-cs/chigame#143]

**Comment by AndrewM131** [comment]
Description: We want to implement a view in which a user can see their historical information, and leave an open area that other groups can code information on to display things such as past matches, achievements, etc.

**Comment by AndrewM131** [comment]
Update: PR was made, and a style change was asked, and then addressed. No big issues with the code in the review, and works as expected.

**Comment by AndrewM131** [comment]
Closing comment: We created a new view that can be accessed by any user to view another user's stats, such as games played, games won, etc. The actual code of statistics has not been implemented as it wasn't in dev branch before this task was created. This will be something we will return to in a future task and implement the actual stats of a user. 
During the sprint, Henrietta and I met two times, once during the first week of the sprint, and another time right before the end of the sprint. When we met, we discussed what files we would use, and how we would implement it. Then I coded on my laptop while Henrietta reviewed my code and added any additional comments on if anything was missing.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
This issue and its associated PR did a good job of setting up a new page for user stats. I would have liked to see more status updates, as your closing statement explains a lot more steps throughout the process of completing the issue.
