### ISSUE TITLE
Install example instance of django-machina to the chigame sandbox directory

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#145]
The objective of this task is to set up a default example instance of the django-machina forum library, verify that it runs correctly, and upload it to the chigame repo's sandbox directory (`src/sandbox`). This example instance will serve as the basis of a mock implementation ( #149 ) of the chigame forum that will be used for testing and evaluation purposes ( #99 ).

**Comment by joshuamonroe** [comment]
Issue #174 has been opened to create the chigame sandbox directory.

**Comment by joshuamonroe** [comment]
The sandbox directory has been added and issue #174 has been closed. I've also added the django-machina demo to the sandbox and submitted a pull request to merge it into dev.
- #204

**Comment by joshuamonroe** [comment]
Closed after successfully merging and closing PR #204 . Thanks to @Benjoman12 for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
For future reference, if someone reviewed the PR for an issue, they should not also be assigned to that issue! 

Great work! Love you expressing your appreciation in the closing comment :)
