### ISSUE TITLE
Install example instance of Misago to the chigame sandbox directory

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#146]
The objective of this task is to set up a default example instance of the Misago forum library, verify that it runs correctly, and upload it to the chigame repo's sandbox directory (exact location TBD). This example instance will serve as the basis of a mock implementation ( #150 ) of the chigame forum that will be used for testing and evaluation purposes ( #100 ).

**Comment by joshuamonroe** [comment]
Issue #174 has been opened to create the chigame sandbox directory.

**Comment by bburgess19** [comment]
# Closing comment
We installed an example Misago instance and verified that it worked correctly. We then uploaded that code in the containerized `sandbox` directory for testing purposes.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
This could have done with more updates on the process of getting the example instance.
Other than that. Good work! Meaningful summary for a relatively small issue.

Thank you for your work
