### ISSUE TITLE
(users) Make id for a User match id for a UserProfile

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#148]
User and UserProfile are in one-to-one relationship. A lot of code would be more readable and intuitive (especially profile view function) if the User instance share the same id as its UserProfile.

**Comment by omarelkashef** [comment]
Closing statement: We realized that instead of doing this we can just use the OneToOne field to access the User from UserProfile as in https://docs.djangoproject.com/en/4.2/topics/db/examples/one_to_one/. So we are closing this issue.

**Comment by elizabethli31** [comment]
Issue Score: Unsatisfactory

Comments:
Marking this as unsatisfactory simply because this issue was resolved by Borja's explanation and the OneToOneField was already in the code.
