### ISSUE TITLE
Implement a simple mockup of the chigame forum in the django-machina sandbox instance

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#149]
The objective of this task is to implement a simple mockup of the chigame forum in the django-machina sandbox instance created in issue #145. The mock implementation should consist of a basic outline of the potential layout and structure of the chigame forum, without the need for implementing new functionalities or involving any sort of detailed customization. The focus should be on ensuring that the implementation process is straightforward and well-documented. Any challenges encountered during the process, as well as any potential issues that may arise in future development, should be recorded for inclusion in the django-machina evaluation report in issue #99.

**Comment by joshuamonroe** [comment]
I've created a mock fixture for use in the sandbox django-machina demo and submitted a pull request to merge it into dev.
- #254

**Comment by joshuamonroe** [comment]
Closed after successfully merging and closing PR #254 . Thanks to @Benjoman12 for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Nice work! Incredibly descriptive and meaningful summary.
