### ISSUE TITLE
Implement a simple mockup of the chigame forum in the Misago sandbox instance

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#150]
The objective of this task is to implement a simple mockup of the chigame forum in the Misago sandbox instance created in issue #146. The mock implementation should consist of a basic outline of the potential layout and structure of the chigame forum, without the need for implementing new functionalities or involving any sort of detailed customization. The focus should be on ensuring that the implementation process is straightforward and well-documented. Any challenges encountered during the process, as well as any potential issues that may arise in future development, should be recorded for inclusion in the Misago evaluation report in issue #100.

**Comment by bburgess19** [comment]
Closing this issue. Didn't fully complete the mockup as we realized early that this wouldn't be a viable solution. View issue https://github.com/uchicago-cs/chigame/issues/100 with more detailed notes.

**Comment by majorsylvie** [comment]
Issue Score: Ungradable



Comments:
This is a non-gradeable issue as it was not completed and instead closed as not planned.
