### ISSUE TITLE
Create the update view for tournaments

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#151]
In this task, we would like to create an update view for tournaments, on which users (currently restricted to admins, and will get changed later when we figure out a way to allow non-admin users to create or edit tournaments) will be able to update (edit) all the tournaments created (or the tournaments created by themselves for non-admin users). This is a part of the CRUD pages.

**Comment by MikeChen012345** [comment]
We have implemented the update view for the tournaments. Currently, only staff members are allowed to edit most of the information about a tournament. This would be changed later to allow non-admin users to access the functionalities with restrictions (issue #172 ). The related pull request is #188

**Comment by MuyanXie** [comment]
Closing Statement:

In this issue, @jb-01 worked on discussing with the team about the necessity of having an update view. @MikeChen012345 and @MuyanXie worked on implementing these features in code

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice job implementing this view! Also, great comments detailing the changes to be covered in future PRs.
