### ISSUE TITLE
Implement the "leave lobby" feature

### ISSUE THREAD

**Issue by xylucien** [uchicago-cs/chigame#152]
Implement a "Leave Lobby" button let's a user leave a lobby only if they have joined the lobby. For this issue, this will be done by removing said user from Lobby.members, else the user will be led to a 404 page.

**Comment by xylucien** [comment]
update: integrated with join button. Everything seems fine.

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged successfully as task is finished

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Would like to see more detailed updates next time, but good work anyways!
