### ISSUE TITLE
Adding Filtering capabilities to the Game List View API Endpoint

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#159]
Adding querying capabilities to the Game list view endpoints: `/api/games/?property=key`

For example, we may want to find all the games that have `min_players=1` or `max_players=5`. We may want to add the functionality of having some way to query the our Games dataset instead of always just returning all the games in our database. To do this, we can use the Filtering class in Django.

Example Endpoints:

`/api/games/?min_players=1` or `/api/games/?max_players=5`

We will know when this issue is completed when we can correctly filter our list of games using the `max_players`, `min_players`, and `name` attributes of the Game model

**Comment by abrahmasandra** [comment]
Added a GameFilter class within filters.py file in the API app. This allows the user to filter by the `name`, `min_players`, or `max_players` attribute. This querying tests for equality for the min or max players attribute. 

I decided to make the querying with the name return all games where the `name` attribute contains the string passed into the query. This allows for more natural searching capabilities, so the user can pass a partial string in and still get the game they are looking for back.

**Comment by abrahmasandra** [comment]
Querying capabilities for game list view is fully functional now. The `Django-filter` package was used in order to create the `FilterClass` needed to apply these queries to the views classes (`GameListViews`). The `django-filter` package has been added to the `requirements.txt` file and added to the list of INSTALLED_APPS for the chigame project.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
