### ISSUE TITLE
Change Notification model into Announcement

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#162]
During our group meeting on Monday, Rafael contacted the User Profile group and found that the group has created a Notification model for sending notifications. Since we don't want overlapping here, we would like to change the Notification model in our games/models.py into an Announcement model, which is used to send announcements to multiple users by sending a Notification to each user in the "recipients" attribute of the Announcement model.

**Comment by MuyanXie** [comment]
Closing Statement:

@MikeChen012345 worked on figuring out the best current approach to change the notification into the announcement
@MuyanXie worked on putting together the code that will solve this issue
@rqueiroz20 worked on contacting the other team to communicate our needs and acquire necessary documents

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Similar comments to the PR - nice work! Announcement model makes much more sense for the purposes of the tournament, and you guys did a great job leveraging the existing Notification model for the functionality you wanted.
