### ISSUE TITLE
Create and show single-elimination brackets on the tournament-detail-view

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#163]
We want to let the users see the match brackets in the tournament. The number of brackets depends on the number of players, and if needed, some brackets may contain only one player (when there is an odd number of players in that round). When the tournament is created, all the players will be randomly assigned to a match with another player. Since this is for a single-elimination tournament, each time the tournament gets to the next round, the number of brackets is divided by the maximum number of players that can play the game (rounds up), and the match assignment for that round is randomly created based on the result of the last round.

**Comment by MikeChen012345** [comment]
We have implemented the brackets feature. Currently, when a tournament is created, players in the tournament will be automatically randomly assigned to different matches (brackets). When one round of matches is done, a function is provided in tournaments_function.py to randomly assign winners of the last round to brackets for the next round. Note that the concept of a "round" is not implemented right now since games have not been implemented and hence the result of a match cannot be determined. We may add this "round" later in other pull requests. Also note that currently, the brackets are created as soon as the tournament is created. This is for testing purposes. However, after the concept of "registration deadline" is added, the brackets should be created after the registration deadline has passed so that users have time to sign up for and quit a tournament. The related pull request is #189 .

**Comment by MuyanXie** [comment]
Close statement:

@MikeChen012345 worked on the main code logic for brackets
@MuyanXie worked on the logic of single elimination and discussed details about elimination together with brackets
@Riyush Helped with putting together the documentation and discussion details about the brackets and best practices

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
The functions related for this issue are a really nice addition for both the backend functionality and future renditions of frontend. My only comment is that this issue spanned two sprints, but great work providing a thorough explanation for the issue and detailed closing comment.
