### ISSUE TITLE
Update the API Endpoints dealing with Game model (List and Detail Views)

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#164]
Pull Request #153 changed the Game model to be more fleshed out, taking inspiration from BoardGameGeeks. Due to the changes in the model, we need to now change our API Endpoint Views, so that the model attributes are returned correctly. There are additions to the model, as well as changes to the existing attributes of the Game model.

**GOAL**:

Update the API views and serializers dealing with the Game models, so that it integrates the new attributes added to the Game models into the response outputted from the corresponding API endpoints. We will know that the issue is completed when this is the case.

**Comment by abrahmasandra** [comment]
The new update of the Game model in PR #153 added many new attributes in the model. I split the `GameSerializer` class into two serializers `GameListSerializer` and `GameDetailSerializer`. This switch was made because we generally want much less information about each game in the list view than the detail view. In the Game list view, I kept only the fields `id` and `name` in order to identify each individual game and enter the game's detail view if necessary. In the Game detail view, I added all the fields using `fields = '__all__'` because we would want all details about a specific game in this view.

**Comment by abrahmasandra** [comment]
Updated the GameListView and GameDetailView to use the serializers that I changed above

**Comment by abrahmasandra** [comment]
Reverted to using `fields = "__all__"` for both the List and Detail views. The reason for this is the List view also takes care of POST requests (instead of just GET requests), which require more information. Instead of making separate Serializers for the GET and POST requests of the List View, it is simpler to just use `fields = '__all__'` for both the List and Detail views.

**Comment by abrahmasandra** [comment]
Closing Comment:

Updated the list and detail view endpoints of the `Game` model (specifically the URLs `/api/games/` and `/api/games/<game_id>`) so that they display all of the attributes of the `Game` model. Previously, only the `name`, `description`, `min_players`, and `max_players` fields would be shown through the list and detail views

**Comment by majorsylvie** [comment]
Issue Score: Excellent
