### ISSUE TITLE
Update the API Tests dealing with Game model (Testing List and Detail Views) 

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#166]
In issue #164, we detailed the ways that the Game endpoints needed to be changed in order to have functional API Endpoints that display and allow for the creation of Game objects with all the new attributes added to the models. Now, we also need to update the tests for these API Endpoints, because the old tests did not take into account all the new attributes that would be added to the Game model. 

Changing these tests are mandatory for the PR #165 to pass, because these tests need to pass before the new code for the List and Detail views can be merged to the `dev` branch of the repository.

**Comment by abrahmasandra** [comment]
Because the `Game` model is getting more and more complex with additional attributes, we want our tests to be dynamic and work with different iterations of the model. To do this, we should add and use `Factories` that will make the testing more dynamic and easier to edit with changing models.

**Comment by abrahmasandra** [comment]
Created `GameFactory` class to use in a `test_api.py` file to test the API endpoints dealing with the Games model (List Games and Detail view Games). Needed to also create `CategoryFactory` and `MechanicFactory`, as they were models that were used for relationships within the Game model.

**Comment by abrahmasandra** [comment]
**Important**: These tests MUST be updated before PR #165 is merged, because the old tests are not accurate/do not pass with the updated Game model.

**Comment by abrahmasandra** [comment]
Tests that were created/adapted:

1. Test Getting the Detail View of a Game using API
2. Test updating Game information using API
3. Test deleting game using API
4. Test Getting List View of games using API

I chose these tests because they cover all HTTP requests that can be made with the API (GET, DELETE, PATCH).

**Comment by abrahmasandra** [comment]
Testing the POST request will be updated AFTER PR #165 is merged, because the change in the Game Serializer is necessary to test POST requests, as the Serializer defines how to format the JSON that goes as the data into the POST request

**Comment by abrahmasandra** [comment]
Closing Statement: Implemented `Factory` classes to make testing more dynamic and easier to edit with changing models. Edited the tests for the Games List and Detail API Views to use the Factory classes to generate mock Game models during testing.  The specific tests implemented, and the reasons for implementing the tests, are thoroughly documented in the comments above.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job with updates and linking relevant issues/PR's!
