### ISSUE TITLE
Document Notifications model in Wiki page

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#168]
Create a documentation for the Notification model on the wiki page that includes attributes, methods and example usage of the model.

**Comment by omarelkashef** [comment]
Closing statement: the documentation was uploaded to  https://github.com/uchicago-cs/chigame/wiki/Users-&-Friending-~-Notification-Model-Documentation
@omarelkashef & @24raniwalar specified how to use the model and how it works.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice work! The wiki page is extremely clear and detailed. The addition of usage examples is really nice and will be incredibly helpful for future teams. Summary description for this issue is a little terse, but otherwise great job!
