### ISSUE TITLE
Write up ERD.md/TABLES.md for updated Game and related models

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#169]

**Comment by majorsylvie** [comment]
@ptlin25 is this issue still open? it has no assignees, nor description, nor updates.

**Comment by ptlin25** [comment]
We have decided this issue is unnecessary at this point, so it will be closed as incomplete

**Comment by majorsylvie** [comment]
Issue Score: Ungradable

Comments:
ungradeable since it closed as incomplete
