### ISSUE TITLE
Add support to games search bar to allow users to search games by author as well as title

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#170]
Currently, the game search bar can only search by the game name or by category names. We will add functionality to the game search bar, so that users can search the games by author. This involves editing the filter options in `games/views.py`, so that the games can be queried by the publisher's name or by the artists and designers

**Comment by ptlin25** [comment]
Created branch `game-management/search-by-creator` for this issue

**Comment by ptlin25** [comment]
I have added code that supports querying for games by the publisher's name, artist's name, or designer's name. My initial concern is that the search results will be extremely long for a very short/vague query.

**Comment by ptlin25** [comment]
Another concern is that users may not understand that the query also searches for games whose publisher's name, artist's name, or designer's name matches the query.

**Comment by ptlin25** [comment]
This issue has been closed as the game search bar now supports searching by producer's name, artist's name, or designer's name. Next steps include removing duplicates from the search results and potentially adding more drop down options, so it is more clear why the results were returned. For example, separating the search for games by name and search for games by producer name.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! Particularly good job adding descriptive comments as you go. I felt like I understood your flow and and though process as you worked, which is amazing!

Thank you also for explicitly listing next steps! 

Be proud of your work.
