### ISSUE TITLE
Add support for non-admin users to create or edit tournaments

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#172]
This issue is a direct continuation of issue #173 . In this issue, we will discuss how we would allow non-staff users to create or edit tournaments, with a thorough documentation of the methods and a coming PR finalizing the changes

Documentations on Non-staff users:

- Allowed to use tokens to create Tournaments (contact the User team to get this done, which is also considered a scope within this issue).
- Allow to have partial edit control over their own tournaments; some actions shall be done by contacting staff users for assistance.
- Also for editing: would not be able to remove/add matches/players to a tournament.
- Allow to join tournaments that they have access to.
- Are not allowed to delete/disable the tournament they created but should contact staff users to do so because the deletion of a tournament can lead to a bunch of different events that need to be handled.
- Cannot access the tournaments that are not open to them.

**Comment by MuyanXie** [comment]
@MikeChen012345 I think one issue regarding a possible PR is that should we include a way for the admin users to create/edit tournaments in the form of views/apis? Definitely they can just create a tournament by modifying the database, but I'm just wondering if you think we should provide a different function in views.py for admin users to create/edit tournaments

**Comment by MikeChen012345** [comment]
For admin users to create, update, and delete a tournament, the approach is to use the link that only appears on the detail view and list view if users are logged in as an admin user. This has been implemented in the CRUD pages. However, since the CRUD pages have been split into 3 pull requests, currently the links are removed. We may need to add them back later.

**Comment by MuyanXie** [comment]
Reminder: we need to add support to distribute new tokens every month

**Comment by MuyanXie** [comment]
@MuyanXie worked on @Riyush worked on finalizing the logic of non-admin creating tournaments. @MikeChen012345 worked on coding and doing the details

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great start to making the tournaments feature more dynamic. Also, nice description that clearly defines that this task covers. My only comment is that this issue took two sprints to complete.
