### ISSUE TITLE
Create a sandbox directory in the chigame repo

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#174]
This task is to create a new sandbox directory in the chigame repo to be used for testing and evaluation of the django-machina ( #145 ) and Misago ( #146 ) forum libraries, and also to be available for future use. Per the guidance of @majorsylvie, this directory should reside at `/src/sandbox`.

**Comment by joshuamonroe** [comment]
I've created the sandbox directory and submitted a pull request to merge it into dev.
- #175

**Comment by joshuamonroe** [comment]
Closed after successfully merging and closing PR #175 . Thanks to @giomhern for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Happy to see the sandbox alive! 

Thank you for providing links to the relevant PR! Makes this straightforward minor task very readable and navigable.

For posterity, the reason the sandbox was put in `src/sandbox` was so any other team may use the sandbox for demos and experimentation that is related to chigame but not necessarily in it.
