### ISSUE TITLE
Make new Game model attributes nullable

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#178]
Many of the new attributes that have been added to the Game model should be nullable (not required). However, this is currently not working because `blank=True` was not set for these attributes. As a result, trying to fill out a form without filling out these attributes creates an error. The attribute `blank=True` needs to be added to all of the attributes that are not required.

**Comment by ptlin25** [comment]
Branch `game-management/null-attributes` created for this issue

**Comment by ptlin25** [comment]
This issue has been completed by pull request #179. The optional attributes of the Game model are now properly created, so they can be left blank.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work fixing the bug and staying with our scrum board! 

Appreciate linking the relevant PR in the closing comment.
