### ISSUE TITLE
Join tournament functionality

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#181]
This functionality allows users to sign up for the tournament on the tournament-detail view and tournament-list view pages. There is a button named "join" that puts the user entity into the "players" table of the tournament. The user can also quit the list before the match assignment (brackets) starts.

**Comment by MikeChen012345** [comment]
This functionality allows users to sign up for the tournament on the tournament-detail view and tournament-list view pages. There is a button named "join" that puts the user entity into the "players" table of the tournament. The user can also quit the list by clicking the button named "withdraw". If the user has already joined the tournament, an error message claiming that the user has already joined the tournament will be displayed. The same would happen if the maximum number of players has been reached. If the user is not in a tournament and clicks the "withdraw" button, the user will also receive an error message claiming that the user has not joined the tournament. Note that some more condition checks shall be done after the registration deadline is implemented: the join and withdrawal shall be done before the match assignment (brackets) starts, etc. The related pull request is #190 .

**Comment by MuyanXie** [comment]
Closing Statement:

@MikeChen012345 worked on coding the solution to this issue
@MuyanXie worked on documenting and researching the different scenarios in which the tournament can be joined
@Riyush  worked on how joining an already-joined tournament and withdrawing from a not-joined tournament may result in an error message 

@jb-01 reviewed our code and provided very valuable comments. Thanks!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice functionality that actually lets users participate in tournaments. I would have liked to see more status updates, but good work regardless.
