### ISSUE TITLE
Add helper filtering methods to Notification

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#182]
We need helper methods that facilitate using the new Notification model. Currently we can only get and filter by actor, but other important methods include get and filter by receiver in order to display in inbox and also filter by unread, read, deleted and mark multiple notifications as deleted, undeleted, read, unread. Another helpful method is to filter by type of notification.

**Comment by omarelkashef** [comment]
Closing statment: In this pull request, we introduced helpful methods that streamline essential operations for the Notification model. With these additions, we can now retrieve and filter notifications by receiver. Additionally, we enabled filtering by unread, read, deleted, and notification type the ability as well as marking multiple notifications as deleted, undeleted, read, or unread.

@24raniwalar worked on the mark_x() and is_x() methods
@omarelkashef worked on the filter and get methods

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Same comments as on the PR. Great work!
