### ISSUE TITLE
Create a simple fixture for testing purposes

### ISSUE THREAD

**Issue by xylucien** [uchicago-cs/chigame#185]
It is necessary to create some games and lobbies fake data and store them in a fixture to speed up the testing process.

**Comment by xylucien** [comment]
added a fake game and a fake lobby to the fixture.

**Comment by xylucien** [comment]
the fixture is now placed under games/games-data.json

**Comment by xylucien** [comment]
closing statement: the fixture is not available and is placed under the right location.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Small fixture that's been improved upon now. Summary is a little terse, but good updates on the progress of this issue!
