### ISSUE TITLE
Create a registration deadline feature for tournament

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#201]
Right now, players in a tournament are assigned to brackets right after the tournament is created. However, in a realistic setting, users should be allowed to sign up for the tournament and quit before the registration deadline. It is after the deadline that the brackets are created. We need to create this registration deadline feature accordingly. This change will affect the tournaments_brackets (# 189) and join_tournament (# 190) functionalities.

**Comment by MikeChen012345** [comment]
This feature would be implemented after issue #237 has been dealt with. 
- The join_tournament branch should be updated so the join and quit buttons are only shown when the tournament status is “registration open”. Edge case: However, if a user clicks on these buttons when the status is “registration open” (so the button is there), but when the request is received, the status is different, then an error message should be displayed (“Sorry, the registration period has already closed”).
- The tournament bracket branch should be modified so the brackets are created after the tournament status is “registration close”. However, a way to check the time should be considered (one way to do this is that when the first user accesses the page, if the status is “registration close” and the brackets have not been created, then the create_brackets function is called, so everyone else after that can see the brackets).

**Comment by MikeChen012345** [comment]
Issue #237 has been dealt with in pull request #247 . Once the branch is merged, the changes on the join_tournament and tournament_bracket features can be made.

**Comment by MikeChen012345** [comment]
- The join_tournament functionality has been changed to only allow users to join and withdraw when the tournament status is "registration open". Also, the error message to reject join and withdraw actions after the status has changed is implemented.
- The tournament bracket is now created after the status is "registration close" and when the page is first accessed after the status has changed.
- A check_and_end_tournament function has been added to end the tournament when the tournament end date is reached, and matches that have not finished are automatically forfeited.
- "Join match" and "spectate" buttons have been added to the tournament detail view and are displayed when the status is "tournament in progress". However, since the related functionalities have not been implemented yet, the two buttons do nothing currently.

**Comment by MikeChen012345** [comment]
The related pull request is #328.

**Comment by MikeChen012345** [comment]
This issue is resolved by pull request #328. @MikeChen012345, @MuyanXie, and @rqueiroz20  worked on the code. The HTML parts and the views.py were mainly created by @MikeChen012345 and @MuyanXie, and @rqueiroz20  focused on different ways to implement the registration period feature.
@jb-01 helped us review the code and made sure that the code worked as expected. Thanks!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Wonderful improvement from previously allowing users to join at any time.
