### ISSUE TITLE
Update models.py to support more functionalities

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#206]
Some future functionalities require a change in models.py for support. We want to add a field to the tournament model to represent the number of winners and modify the tournament model to provide support to the tournament bracket functionality. Also, we plan to add support for the admin interface to handle models.

**Comment by MikeChen012345** [comment]
In this #209 pull request, we have made some changes to

allow developers to access the tournament models through the admin interface (admin.py).
add a num_winner field to the tournament model to keep track of the number of winners for a tournament.
make the matches and players fields of the tournament model optional during the creation and edition of a tournament such that users can join and withdraw from a tournament by themselves instead of from direct assignment. Also, matches are made optional because they should be created through the bracket assignment mechanism in issue.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good job! Same comments as the PR - minor but important change.
