### ISSUE TITLE
Tournaments Navigation Link

### ISSUE THREAD

**Issue by rqueiroz20** [uchicago-cs/chigame#207]
Currently, ChiGame does not have a way to access the list of tournaments for a user logged into ChiGame. This issue would add a link to the navigation bar that would allow users that are logged in to see the list of tournaments.

**Comment by rqueiroz20** [comment]
The Tournaments link to the navigation bar on ChiGame has been successfully implemented and merged into the main ChiGame repository. Here is a summary of what everyone did for this issue:

- I wrote the code that modified `base.html` initially.
- Riyush Thakur noticed that I had forgotten about the user authentication, so he wrote the code for that.
- I created the PR and assigned Zihao Chen to review it.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work! Same comments as on PR - minor but very useful.
