### ISSUE TITLE
User Stories for Game API Endpoint Development for Retrieving and Posting Game Data

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#212]
**Goal**: To create user stories for a GET endpoint at /api/games to retrieve a list of existing games, providing essential information such as game titles, genres, and release dates. This will empower users and external systems to easily access and display game data. To create user stories for a POST endpoint at /api/games to enable the addition of new games to the system. This feature will facilitate the submission of game details, including titles, genres, and release dates, contributing to the expansion and enrichment of the game database.

These user stories drive the implementation of a versatile API endpoint, enhancing the overall functionality of the chigame platform by enabling seamless access to existing game data and facilitating the addition of new games through a standardized and efficient process.

**Comment by cuyakonwu** [comment]
#  POST Games Endpoint:
-Admin user Michael wants to create a game with a minimum of 1 player and maximum of 4. The game is titled Upturn and has a very generic description. He uploads an image that will be displayed whenever users view the game, and states the rules of the game. The suggested age is 10+ and will be inputted as 10. The expected playtime will be set to 45 minutes with no minimum or maximum specified. The complexity of the game will be set to 2, and the category is listed as "Other", with the uplift and upturn mechanics being highlighted. Upon posting, the game will receive its Board Game Geek ID which is autoincremented by django.

-Users that opt to will automatically be notified of this incredible new game through an automated GET API. They will be able to see the cover image of this game, its rules, description, complexity, genre, mechanics, minimum and maximum players, the age restriction, and estimated playtime.

**Comment by cuyakonwu** [comment]
#  POST Games Endpoint:
-Admin user Michael wants to create a game with a minimum of 1 player and maximum of 4. The game is titled Upturn and has a very generic description. He uploads an image that will be displayed whenever users view the game, and states the rules of the game. The suggested age is 10+ and will be inputted as 10. The expected playtime will be set to 45 minutes with no minimum or maximum specified. The complexity of the game will be set to 2, and the category is listed as "Other", with the uplift and upturn mechanics being highlighted. Upon posting, the game will receive its Board Game Geek ID which is autoincremented by django.

-Users that opt to will automatically be notified of this incredible new game through an automated GET API. They will be able to see the cover image of this game, its rules, description, complexity, genre, mechanics, minimum and maximum players, the age restriction, and estimated playtime.

# GET Games Endpoint:
As a game enthusiast, Shannon want to retrieve detailed information about the recently posted game "Upturn" through a GET API endpoint at /api/games, so she can stay informed about new and exciting additions to the chigame platform.

- The GET API endpoint at /api/games successfully retrieves information about the game "Upturn."
- She can view the cover image, rules, description, complexity, genre, mechanics, minimum and maximum players, age restriction, and estimated playtime for the game.
- The retrieved data includes the auto-incremented Board Game Geek ID assigned to the game by Django.

**Comment by cuyakonwu** [comment]
With the successful creation and implementation of the POST and GET endpoints for the `chigame` platform, a user-friendly gaming environment will be established. Admin user Michael, can use the POST endpoint, can effortlessly add new games like "Upturn," complete with details on player range, age restrictions, playtime, complexity, and unique mechanics. This submission adds info to the database and ensures that gamers have access to many different games. Concurrently, the GET endpoint creates an informative user experience for game enthusiasts like Shannon, who can now access information about games, including visuals and specific game mechanics.
[Link Here](https://github.com/uchicago-cs/chigame/wiki/API-~-User-Stories)

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Good job following the requirements for an issue! 

Your summary makes specific mention of the kinds of endpoints you are considering for these user stories. 

Then you actually wrote the stories, putting them as updates so how you progressed is clear.

And you added a closing comment which links to the final product of your wiki page.

The language of your closing comment is quite odd though, describing the world of the user stories, which is not relevant. For this kind of work the closing comment needs to be "here is the works thats been done, here are the challenges I went through / things on my mind as this finishes, here's what's been produced [link to wiki]".

Overall, this is more in line with what we want, keep going!
