### ISSUE TITLE
Integrate the django-machina forum library into chigame

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#213]
The purpose of this task is to integrate the django-machina package into the chigame project. Detailed instructions can be found  in the django-machina docs, [here](https://django-machina.readthedocs.io/en/latest/getting_started.html). In summary, this task will require making the following changes:
- Adding django-machina to the requirements
- Configuring the project's django settings for django-machina
- Adding the django-machina URLs to the project

**Comment by joshuamonroe** [comment]
I've integrated the django-machina forum library into the chigame project and submitted a pull request to merge it into dev.
- #255

**Comment by joshuamonroe** [comment]
Closed after successfully merging and closing PR #255. Thanks to @bburgess19 for reviewing the PR. During the review process, it was brought to our attention by @majorsylvie that there should be a document detailing the use of django-machina in chigame. To this end, issue #270 has been opened.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! 
Thank you for linking relevant PR's and relevant created issues.
