### ISSUE TITLE
Align forum terminology standards with django-machina

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#214]
Due to differences in terminology between the previously [established standard](https://github.com/uchicago-cs/chigame/wiki/Forums-~-Standard-Terminology) and [django-machina](https://django-machina.readthedocs.io/en/latest/glossary.html), the purpose of this task is to align the existing standard to match the terminology used in the django-machina project. This will align the terminology in such a way as to maintain consistency between the django-machina code base and any documentation, both internal and external, while taking far less effort than would be required to revise the terminology used in the django-machina code base.

**Comment by joshuamonroe** [comment]
I've completed updating the [terminology standards](https://github.com/uchicago-cs/chigame/wiki/Forums-~-Standard-Terminology) to align with the terminology used in django-machina and made all necessary updates to the [ERD](https://github.com/uchicago-cs/chigame/wiki/Forums-~-Entity-Relationship-Diagram-(ERD)) and [user stories](https://github.com/uchicago-cs/chigame/wiki/Forums-~-User-Stories).

#### Summary of Changes:
- Subforum -> Forum
- Thread -> Topic

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Love the summary of changes! 
And the links in the closing comment.
