### ISSUE TITLE
Add a link to the forum to the chigame navigation bar

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#215]
The purpose of this task is to add a link to the forum to the chigame navigation bar. This will ensure that the forums can be easily reached from rest of the chigame website.

**Comment by Benjoman12** [comment]
I've added a link to the forum on the chigame navigation bar and submitted a pull request to merge it into dev.
* https://github.com/uchicago-cs/chigame/pull/272

**Comment by joshuamonroe** [comment]
Closed after successfully merging and closing #272. Thanks to @Benjoman12 for making the PR, which was reviewed by myself with additional comments from @bburgess19.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! Thank you for the good closing comment @joshuamonroe
