### ISSUE TITLE
Add the chigame navigation bar to the forum pages

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#216]
The purpose of this task is to add the chigame navigation bar to the top of all forum pages. This will ensure that the forums are integrated with the rest of the chigame website and that users are able to easily navigate to other parts of the platform.

**Comment by Benjoman12** [comment]
#272

**Comment by Benjoman12** [comment]
I've added the chigame navigation bar to the forum page and submitted a pull request to merge it into dev.
* https://github.com/uchicago-cs/chigame/pull/272

**Comment by joshuamonroe** [comment]
Closed after successfully merging and closing #272. Thanks to @Benjoman12 for making the PR, which was reviewed by myself with additional comments from @bburgess19.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work!
Clean and simple for a small task that was primarily contained in PR.
