### ISSUE TITLE
Exploring Non-Admin User Capabilities in Tournament Creation: Collaborative Discussion with Tournaments Team

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#217]
Initiate a discussion with the Tournaments Team to understand the scope of tournament creation capabilities available to non-admin users. This collaborative effort aims to examine existing user stories, shedding light on the diverse functionalities and features non-admin users can use when creating tournaments on the ChiGame platform. The goal is to identify potential enhancements, and ensure that the tournament creation process aligns with potential non-admin users, and between the API and Tournaments team.

**Comment by cuyakonwu** [comment]
I reached out to the team, and received a link to their documentation [here](https://github.com/uchicago-cs/chigame/wiki/Tournaments-~-Limitations-for-Users-Creating-Tournaments)

**Comment by cuyakonwu** [comment]
As stated in the wiki linked above, non-staff users are allowed to use tokens to create Tournaments, have partial edit control over their own tournaments; some actions shall be done by contacting staff users for assistance. However they are not allowed to remove/add matches/players to a tournament, delete/disable the tournament they created.

This should give a good idea of how non-staff users are able to access the tournaments api endpoints in future versions of chigame.

**Comment by cuyakonwu** [comment]
I appreciate the collaborative efforts of the Tournaments Team in engaging with the exploration of non-admin user capabilities in tournament creation. The insightful discussions and examination of existing user stories have provided valuable insights into the functionalities available to non-admin users on ChiGame. As we work towards identifying potential enhancements, our collective goal remains aligned—to ensure a seamless tournament creation process that caters to the diverse needs of non-admin users. I look forward to the ongoing collaboration between the API and Tournaments team as we strive to optimize the user experience and foster inclusivity in tournament creation. Thank you to all contributors for your dedication and valuable insights throughout this discussion.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
