### ISSUE TITLE
Implement django filter on Lobby List view

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#219]
**Goal:** The lobbies list page lists all lobbies with no specific organization. To make lobby searches more efficient, we want to implement advanced filtering capabilities where users can choose to display only lobbies with certain games, players, or match start times. We've done the research for what we need to do in order to have the filter appear on the view. We need to now decide which attributes we want to allow users to filter in their search.

**Deliverables:**
- Pull Request

**possible mini-steps:**
- create `filters.py` with LobbyFilter class
- identify which attributes we want to allow filters for
- for each attribute:
    - identify the lookup expressions we want
    - add it to `Meta.fields`
- add function to `views.py`
- add filters to HTML template

**Comment by jiyeongchloe** [comment]
UPDATE: forked a `matches/lobby-django-filters` branch for the issue.

I've come up with a possible list of mini-steps for this issue:
- create `filters.py` with LobbyFilter class
- identify which attributes we want to allow filters for
- for each attribute:
    - identify the lookup expressions we want
    - add it to `Meta.fields`
- add function to `views.py`
- add filters to HTML template

I've also put this in the summary.
feel free to add to/detract from/cross-off things that are done

**Comment by jiyeongchloe** [comment]
pushed `filters.py` with skeleton LobbyFilter class

**Comment by jiyeongchloe** [comment]
added function to `views.py`

**Comment by jiyeongchloe** [comment]
added filter to HTML and requirements.

page and filter work now; we just need more filter fields

**Comment by jiyeongchloe** [comment]
we'll probably want a more realistic fixture with more instances of lobbies and games for testing. Created a separate issue.

**Comment by jiyeongchloe** [comment]
added `lobby_name` and `max_players` filters

**Comment by jiyeongchloe** [comment]
PR #257 requested and needs to be reviewed

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and task is finished.
We added three different filters (that can be used in conjunction with each other) that allow users to search for lobbies that contain the queries the users type in.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Logical selection of filters and well implemented!
