### ISSUE TITLE
Add auto-create chat when a tournament is generated

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#226]
This issue seeks to add the functionality to automatically create a live chat whenever a new tournament is created. Specifically, the main way to implement this would be to add a function that instantiates a new `Chat` object that has the current tournament as its parameter.

**Comment by MuyanXie** [comment]
Update: Due to the update in our model. I wonder if we would like to close this issue or re-define our scope to be "add auto-create chat when a tournament is generated" @rqueiroz20

**Comment by rqueiroz20** [comment]
> Update: Due to the update in our model. I wonder if we would like to close this issue or re-define our scope to be "add auto-create chat when a tournament is generated" @rqueiroz20 

This is a good idea, I will update the title right now.

**Comment by MuyanXie** [comment]
@rqueiroz20 Are you still able to do this PR before the Soft Freeze? If not, we will have to push it to back log

**Comment by rqueiroz20** [comment]
> @rqueiroz20 Are you still able to do this PR before the Soft Freeze? If not, we will have to push it to back log

Yes I am, I just finished the code for it now. Will push my branch now.

**Comment by rqueiroz20** [comment]
This issue led to tournaments automatically having a live chat associated to them when that tournament is created. Some of the specific changes include the following:
- Modifying the `TournamentCreateView` class to also instantiate a new `Chat` object associated with the tournament.
- Adding a button labeled with the tournament name that takes the user to the frontend live chat display.

@MikeChen012345 and @MuyanXie talked over how such a feature would be implemented and the pseudo-code necessary. @rqueiroz20 worked on implementing the code in the branch itself, and @Riyush reviewed the code and made sure it aligned with the pseudo-code.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nicely implemented auto-creation of chat!
