### ISSUE TITLE
Add create and delete messages APIs

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#227]
In this issue, we will try to add a generic endpoint in the backend that is able to accept the create/delete message request from the frontend .js file to finish the user interaction flow. 

## Justification
Per the way we structured our frontend and messages, we can use one endpoint, named ```MessageView```, as a generic entry point for create/delete requests.

- when a create comes, we will accept it, auto-assign it with an incremental token_id, take its null update_on field, and store it in database. Apparently as we have careful structured the message create logic, we need no additional changes/processing at this point
- when a delete request comes, we will simple accept it. The workflow will be the same as create, as basically we are not deleting anything but appending a new message that has a valid value in update_on in it with a null content that indicates this message is deleted

See issue #225 for further details about the message update model for the frontend and backend

## TODO:
- implement an entry point for the create/delete request from the frontend in the form of api
- update models.py to add auto-assign token_id feature, add update_on field
- implement more related codes for this api

**Comment by MuyanXie** [comment]
Closing Statement:

@MuyanXie worked on coding the API and coding the tests for the API. @MikeChen012345 worked on architecture the API endpoint as well as how the API should look like to work together with the frontend. @jb-01 worked on facilitating the review and debugging of a generalized entry point.

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Substantially sized issue but did not include any updates.
