### ISSUE TITLE
Add a update service to update the clients with latest changes in messages in a chat

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#229]
In this issue, we wish to provide a way for the frontend to effectively receive updates from the backend and efficiently update the display to the players, with minimum requirements of reload

We are going to write a view, which upon query will give updates from the token_id held by the frontend, including all the updates to messages as well as new messages. Please notice once a message entry is posted into the database, it will not be modified in any way; Instead, we will use later messages to update or delete it if necessary

Token ID combined with Update On is a new design and should be updated fields to the model. Token ID is designed to reduce the payload in each query and to effectively track changes, with Update On is to effectively keep track of changes to the msg.

**When a msg is created**:
1. A unique PK is created
2. A unique Token ID is created, which is incremental to this specific chat
3. Update On is null, as we are not updating any previous code in this request

**When a msg is updated**:
1. A new msg is created with a new unique PK and unique and incremental Token ID
2. The Update_On will be set to the old message it is updating to

**When a msg is deleted**:
1. A new msg is created with a new unique PK and unique and incremental Token ID
2. The Update_On will be set to the old message it is updating to
3. Content is set to null

**[IMPORTANT] When the user request to read the messages**:
1. The user will send the latest token ID it has from the front end
2. The server will return it with the messages having the token ID greater than the current token ID the frontend has back
3. The frontend can then update the views based on the results from the payload - it can update previous histories of messages if necessary and can add new messages, all dependent on the Update_On field and Content field of the payload entries

By doing so, we will save a lot of bandwidth and provide a feasible way to real-time update and send messages. To be honest, this is pretty complex and need to be reviewed heavily.

References: Adopted some [log update logic](https://levelup.gitconnected.com/logs-and-distributed-systems-ebd3902732bd) from the design of distributed database systems

**Comment by MuyanXie** [comment]
Reminder: This is gonna be the last issue to be finished in the workflow of creating a chat view for the tournaments. To address this issue, we have the following TODOs:

- Add an API endpoint for update service, together with some tests for this API
- Connect this API with a ```getmessage``` method from the frontend to enable our frontend to "subscribe" to the backend for changes and finish the logic by enabling per second updates

Metrics for closing this issue, which indicates that we have finished all issues related to the major logic of the chat:

- The frontend is functioning, enabling users to create and delete messages
- The frontend will auto-update every second

**Comment by MuyanXie** [comment]
Closing Statement:

@MuyanXie worked on coding the frontend and API. @MikeChen012345 worked on reviewing the code and pointing out inefficiencies. @rqueiroz20 worked on peer programming with Sam on the API.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Very clearly defined description of why the update_on attribute is necessary and what it will look like.
