### ISSUE TITLE
Update Filtering Capabilities for Game List API Endpoint with Updated Game Model Attributes

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#230]
The `Game` model recently got updated to contain many more fields -- inspired by BoardGameGeek -- than just the four initial fields (name, description, max_players, min_players). We want our API endpoint to be able to handle filtering by any of the original fields (which we have already done), but also be able to filter by the new fields. Therefore, we need to add the new fields into the `GameFilter` class. 

We will know this issue is completed when we can filter by any field in the updated `Game` model.

**Comment by abrahmasandra** [comment]
Added filtering capabilities for all new integer type `Game` attributes including `year_published`, `suggested_age`, `expected_playtime`, `min_playtime`, `max_playtime`, `min_players`, `max_players`. For all of these attributes, an exact lookup filtering method was implemented (a used can filter with equalities `suggested_age=8`).

**Comment by abrahmasandra** [comment]
For the new `complexity` attribute, which can be a decimal value, an exact lookup is not all that's necessary, because there are so many possible values. Instead, we implemented a greater than or equal to, and less than or equal to filtering methods, which make more sense given that it is not very informative to filter based on an exact complexity match.

**Comment by abrahmasandra** [comment]
Added `lte` and `gte` support for filtering `Game` list views for ALL numeric attributes

**Comment by abrahmasandra** [comment]
Closing Comment:

Updated the filtering capabilities of API `Game` list view. Specifically, now support filtering for all attributes in the `Game` model. All numeric attributes have support for filtering based on `exact`, `lte`, and `gte`. In addition, text attributes can be filtered using `icontains` (which filters by substring match). 

Endpoint implemented examples: 
1. `/api/games/?property1=key1`
2. `/api/games/?property1=key1&property2=key2`
3. `/api/games/?property1__lte=key1&property2__gte=key2`

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Thank you for good updates!
