### ISSUE TITLE
Implement Field Constraints in Game Model

### ISSUE THREAD

**Issue by frowenz** [uchicago-cs/chigame#232]
We need to add specific constraints to the Game model and related models in our Django application to ensure logical consistency. For example, we want to make sure ```min_players <= max_players```. In this issue, we will identify what needs constraints we need to add.

**Comment by frowenz** [comment]
For the ```Game``` model:

1. Player Number Constraints: The ```min_players``` field must always be less than or equal to the ```max_players``` field. This logic needs to be implemented to prevent inconsistencies in player numbers.

2. Playtime Constraints: Implement a check to ensure that ```min_playtime <= expected_playtime <= max_playtime```. This validation is crucial to keep the playtime data logically consistent.

3. Complexity Range Constraint: The complexity field should be a float that ranges between 0 and 5. This constraint must be strictly enforced, possibly through a custom validator.

We can also add in a similar constraints to make sure ```min_players <=  max_players``` in the ```Lobby``` model since it is in the same file.

**Comment by frowenz** [comment]
Closing comments:
A PR implementing these changes been merged. Here is a description of the work that was done:

> I added some basic validation was added to the Game and Lobby models.
> 
> Examples:
> 
> Ensuring min_players <= max_players for both models
> Ensuring this ordering: `min_playtime <= expected_playtime <= max_playtime
> Ensures the complexity field is between the range of 1 and 5 inclusive.
> This also involved making changing to the Games factory and a small tweak to existing tests.
> 
>

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! For a relatively smaller task you provided detailed documentation, a breakdown of your thoughts on what needed to happen, as well as a good closing comment!

Keep moving forward!
