### ISSUE TITLE
Update tournament models to allow registration period and archive features

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#237]
Some changes will be added to the model:
- add `registration start date` and `registration end date`, which show the registration start and end date for the tournament. 
- rename `start date` and `end date` into `tournament start date` and `tournament end date`.
- add restrictions to `registration start date`, `registration end date`, `tournament start date`, and `tournament end date`: The fields need to check that all registration and tournaments start/end date is after the moment that the tournament is created; also, the end date is after the start date; and registration start and end time are before the tournament start and end time. 
- add `tournament status` field (@property). The `tournament status` is calculated based on the tournament start and end date and registration start and end date (possible status: preparing, registration open, registration close, tournament in progress, tournament ended).
- add `archived` (default=False) field. An archived status is set if tournament 1. has closed 2. is marked as archived (because it is important) by admin users. 
- add a `set_archive` method, which takes a boolean argument and sets the `archived` field based on the argument.

**Comment by MikeChen012345** [comment]
The final result is shown in pull request #247 .

- add `registration start date` and `registration end date` fields, which show the registration start and end date for the tournament.
- rename `start date` and `end date` into `tournament start date` and `tournament end date`.
- add restrictions to check the `num_winne`r, `max_players`, and `winners fields`.
- add restrictions to `registration start date`, `registration end date`, `tournament start date`, and `tournament end date`: The fields need to check that all registration and tournaments start/end date is after the moment that the tournament is created; also, the end date is after the start date; and registration start and end time are before the tournament start and end time.
- add tournament `status` field (@ property). The tournament status is calculated based on the tournament start and end date and registration start and end date (possible status: preparing, registration open, registration close, tournament in progress, tournament ended).
- add `archived` (default=False) field. An archived status is set if tournament 1. has closed 2. is marked as archived (because it is important) by admin users.
- add a set_archive method, which takes a boolean argument and sets the archived field based on the argument.
- modify the tournament list view and detail views such that the tournament status, registration start date, registration end date, and archive status are displayed. The archive status is represented by an icon, which will only be presented if the tournament has ended.
- modify the create view corresponding to the addition of `registration start date` and `registration end date`. 
- modify the update view. The dates now cannot be changed once the tournament has been created.

**Comment by MikeChen012345** [comment]
In this pull request,
@MikeChen012345 and @MuyanXie worked on implementing the code, and @jb-01  brainstormed and came up with different kinds of scenarios in which the status should be changed and what checks to be added.
@rqueiroz20 did the review, tested all the features, and provided feedback on whether there might be more possible situations that current checks do not cover. Thank you!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work covering all the possibilities for statuses.
