### ISSUE TITLE
Add an archived view for archived tournaments

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#238]
This issue would be implemented after issue #237 has been done. 
- Create an archived tournament list view to display all the archived tournaments. The information displayed on the archived tournament list view should be the same as that in the tournament list view, but the archived tournament list view should only display archived tournaments. 
- The `set_archive` function is called when an admin user clicks on an “archive” button on the tournament list view, detail view, and the archived tournament list view (displayed if 1. login as an admin and 2. Tournament has ended). (An unarchived button may be added if archived). (This button can be the "archive" star symbols.)
- Add a link of the archived tournament list view to the tournament list view, and vice versa (we can have a small toggle switch with labels showing “all” and “archived” to change the view (i.e., redirect to another view) displayed).

**Comment by MikeChen012345** [comment]
The issue #237 has been dealt with in pull request #247 . Once the branch is merged, the view and button can be created.

**Comment by MikeChen012345** [comment]
The issue has been implemented with these features:
- Create an archived tournament list view to display all the archived tournaments. The tournament information displayed on the archived tournament list view is the same as that in the tournament list view, but the archived tournament list view only displays archived tournaments. 
- The `set_archive` function is called when an admin user clicks on the “archive” star button on the tournament list view, detail view, and the archived tournament list view (displayed if 1. login as an admin and 2. Tournament has ended). If the tournament is archived, then the star is yellow, and clicking it results in unarchiving the tournament; if it is not archived, then the star is white, and clicking it results in archiving the tournament. If a non-admin user visits the page, the "archive" star icon is not a button, so it cannot be clicked.
- Add a button with the text "Switch to Archived Tournament List" to the tournament list view that, when clicked, redirects the user to the archived tournament list view, and vice versa "Switch to All Tournament List".

**Comment by MikeChen012345** [comment]
The related pull request is #329 .

**Comment by MikeChen012345** [comment]
The issue has been addressed by pull request #329. @MikeChen012345 and @MuyanXie worked on creating the archived view and addressed feedback. @jb-01 helped with thinking about whether the archived view should be designed as a separate page or using the same template as the tournament list view.
@rqueiroz20 helped us with reviewing and testing the code. Thanks!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice addition to distinguish options for tournaments list view.
