### ISSUE TITLE
Implement the Create and Delete Message feature in the Chat Page

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#241]
In this issue we will implement the create and delete message feature in the chat page. As the title indicates, it will actually focus on the frontend realization of the feature to send and delete messages, instead of finishing the logic

After finishing a mock version of the frontend as a function API entry point for chat, in this issue we will proceed by adding a nice send box, a send functionality, a gray box that wrap a chat message if clicked, and a button near to the selected message about deleting the message.

## TODO:
1. Add a send message layout 
3. Add a delete message layout
4. Add a send message JS logic
5. Add a delete message JS logic

We would expect that after this issue, we will have a chat frontend that is able to send create and delete requests. At this point, we do not expect it to be full functioning and be able to update messages. We will address this in later issues/prs

**Comment by MuyanXie** [comment]
Closing Statement:

@MuyanXie worked on the coding part of this PR/Issue. @MikeChen012345 worked on suggesting the best way to implement this feature. @rqueiroz20 worked on reviewing this.

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
This was a huge issue that was well implemented, but it lacked any updates for an issue of this magnitude.
