### ISSUE TITLE
Set format_js to false

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#242]
Currently, with format_js set to be true in the djLint configurations, Django template tags, when used with inline JavaScript, is being reformatted due to stylistic issues and causing it to no longer work. Disabling format_js may be an interim solution.

**Comment by ptlin25** [comment]
Setting `format_js=false` is unnecessary. The relevant code can be wrapped with djlint tags to ignore the linter

**Comment by majorsylvie** [comment]
Issue Score: Ungradable

Comments:
ungradeable since it was abandoned
