### ISSUE TITLE
Create an updated fixture for lobbies with realistic names and games

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#248]
**Goal:** We currently only have fixtures with one game instance and one lobby instance. To test lobby filters and other future functionalities, we want to update the fixtures to include more model instances with unique/realistic names rather than simple names like `test lobby1`

**Deliverables:**
- PR

**Comment by jiyeongchloe** [comment]
Added a fixture called `lobby-fixture.json` with more realistic names.

The password for `admin@example.com` is `test`

The emails and passwords for all other users are `userX@example.com` and `fixtureuserX` where `X` is numbers 1-5

**Comment by jiyeongchloe** [comment]
PR #257 requested and needs to be reviewed

**Comment by jiyeongchloe** [comment]
**update:** something must've gone wrong when merging dev with the branch. the fixture no longer works so will have to make a different branch with different PR

**Comment by jiyeongchloe** [comment]
added `matches/lobby-fixture` branch

**Comment by jiyeongchloe** [comment]
added `lobby-fixture-15.json`

This uses the `users_fixture.json` and `games-fixture-5.json` that were already existing. The user passwords are the same as those in `users_fixture.json`

**Comment by jiyeongchloe** [comment]
Associated PR: [PR #279](https://github.com/uchicago-cs/chigame/pull/279)

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and task is finished.

Nat and Chloe: pulled existing user and games fixtures and added 15 lobbies to create a new fixture for lobbies

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
This fixture helped a lot with testing!
