### ISSUE TITLE
Create User Stories on How Admins Use Categories

### ISSUE THREAD

**Issue by giomhern** [uchicago-cs/chigame#250]
Develop a series of user stories that illustrate how administrators utilize categories in forum management. These stories will help in understanding their needs and challenges, leading to better design decisions for our forum management tools.

**Comment by giomhern** [comment]
Develop a series of user stories that illustrate how administrators utilize categories in forum management. These stories will help in understanding their needs and challenges, leading to better design decisions for our forum management tools.

**Comment by Benjoman12** [comment]
Some possible user stories are the following: 

1. Jordan is an administrator on WatchBuddies. They need to create a new category for an emerging topic of interest. They access the admin panel, create the category, set its permissions, and add a description to guide users on what types of discussions belong in it.

2. Mia is an admin who notices a rise in off-topic posts in a specific category. She accesses the category settings to update the rules and guidelines, ensuring that users are clear about the category's purpose. She also moves misplaced discussions to the appropriate categories.

3. Carlos is an admin who reviews the forum's category structure. He analyzes user engagement across various categories to identify which ones are popular and which are underutilized. Based on this data, he decides to merge some categories and promote others on the homepage.

4. Tina is an admin who uses analytics tools to monitor the activity within each category. She wants to understand user behavior and preferences better. By analyzing the data, she identifies trends and patterns, which help in making informed decisions about introducing new categories or modifying existing ones.

@giomhern When you get a chance look these over and make any edits/additions you deem necessary so we can add it to the wiki.

**Comment by giomhern** [comment]
These user stories look good to me! My only comment would be generally on what you mean by the users analytics in 3 and 4. Is that an interface supported from machina itself or something we would have to implement on the admin side? Addressing these comments would be adequate to add these stories to the wiki. @Benjoman12

**Comment by Benjoman12** [comment]
In answer to the first question regarding story number 3 there are built in analytics but for number 4 we would have to integrate that. Given this it is best to exclude story 4. The following are the updated user stories that address the provided feedback. I will add them to the wiki and close out the issue. 
User Stories: 

1. Jordan's Story:
Jordan is an administrator on WatchBuddies. They need to create a new category for an emerging topic of interest. They access the admin panel, create the category, set its permissions, and add a description to guide users on what types of discussions belong in it.

2. Mia's Story:
Mia is an admin who notices a rise in off-topic posts in a specific category. She accesses the category settings to update the rules and guidelines, ensuring that users are clear about the category's purpose. She also moves misplaced discussions to the appropriate categories.

3. Carlos's Story:
Carlos is an admin who reviews the forum's category structure. He uses the built-in analytics interface in the Machina admin panel to analyze user engagement across various categories. This data helps him identify popular and underutilized categories. Based on this analysis, he decided to merge some categories and promote others on the homepage.

**Comment by Benjoman12** [comment]
The necessary comments have been addressed and the stories have been added to the wiki thus the issue can be closed out.

**Comment by Benjoman12** [comment]
The necessary comments have been addressed and the stories have been added to the wiki thus the issue can be closed out.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Nice work! Good job using markdown formatting to make your user stories more readable in the updates.
