### ISSUE TITLE
Develop User Stories on How Users are Using Categories

### ISSUE THREAD

**Issue by giomhern** [uchicago-cs/chigame#251]
This is an issue with the objective of creating detailed user stories that explore how different types of users interact with categories in our forum. The aim is to gain insights into user behaviors, preferences, and challenges related to category usage, ultimately guiding enhancements in forum design and functionality.

**Comment by giomhern** [comment]
Some possible user stories can be the following, while considering functionality some users would want within categories in forums:

1. Sam is a new user on WatchBuddies. They want to explore different topics of interest. On the forum's homepage, they can see a list of available categories to browse through.
2. Alex is a regular forum user who enjoys discussing various topics. After clicking on a category, they can view a list of discussions within that specific category.
3. Emily wants to narrow down her search for relevant discussions. She clicks on a category of interest and sees a filter option to sort discussions within that category by various criteria such as date, popularity, or relevance.
4. David is interested in a specific category and wants to be notified of new discussions. He subscribes to that category to receive email notifications whenever new discussions are posted within it.

@Benjoman12 if you can look these over and make any changes or if you want to add any, that would be fantastic!

**Comment by Benjoman12** [comment]
These look great and do a good job of covering what we brought up in group discussions. As a result I have added them to the wiki and will close out the issue.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! Nice job coordinating with one another via @'ing.
