### ISSUE TITLE
Implement a create view for lobbies

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#256]
**Goal:** We need users to be able to create lobbies. This will be the Create page of the CRUD pages for lobbies.

**Comment by jiyeongchloe** [comment]
forked new branch called `matches/lobby-create`

**Comment by jiyeongchloe** [comment]
pushed a very basic framework for the create view
We need to restrict access to just staff & get rid of some of the fields we don't want to be customized by the user

**Comment by xylucien** [comment]
I believe adding staff access restrictions can be done in a separate issue!

**Comment by xylucien** [comment]
> get rid of some of the fields we don't want to be customized by the user 

> 

Done

**Comment by jiyeongchloe** [comment]
@lucien386 I don't think we can just delete the fields from `forms.py` cause we still need some kind of an input for those fields for the form to work

**update:** I added a new version of `form_valid` function that takes care of this for now!

**Comment by jiyeongchloe** [comment]
I also just realized we don't want to restrict access because we want users to be able to create lobbies whenever they want

**Comment by jiyeongchloe** [comment]
added `lobbies` to nav bar in `base.html`

**Comment by jiyeongchloe** [comment]
Associated PR: [PR #277](https://github.com/uchicago-cs/chigame/pull/277)

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and task is finished.
We instantiated a Create button/link that allows users to create lobbies. There were no restrictions placed on who could create lobbies because we want all users to be able to create them. Users' access to certain attributes were restricted, however, as we don't want users to be able to manually change settings like the host of the lobby and match status.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Summary description was a little too terse, but otherwise good work.
