### ISSUE TITLE
add button to see / make reviews on game detail page

### ISSUE THREAD

**Issue by danielngira** [uchicago-cs/chigame#261]
Include a button in the game detail page from #40 that allows a user to make a review of a game. Make a list view for the reviews as well to display a list of reviews.

**Comment by danielngira** [comment]
Created branch game-management/reviews-page

**Comment by danielngira** [comment]
Made a form ReviewForm for creating new reviews

**Comment by danielngira** [comment]
Updated the GameDetailView with a FormMixin to allow a form to create reviews for games

**Comment by danielngira** [comment]
Made a ReviewListView and a game-review template. Also updated the URLs to include a URL to the game-reviews page for a specific game

**Comment by danielngira** [comment]
Updated the game-detail template page to include a form to create new reviews

**Comment by danielngira** [comment]
Updated the `ReviewForm` to include `is_public` and a `rating` field

**Comment by danielngira** [comment]
![Image](https://github.com/uchicago-cs/chigame/assets/81624602/a6a7c858-dc6b-4f46-a846-9a2c532184bf)

The review list page functions and only shows public games

**Comment by danielngira** [comment]
This issue is closed as per PR #275. Tasks I worked on:

1. I made a `ReviewForm` to allow users to leave ratings and reviews for games. 
2. I updated the `GameDetailVIew` to render the form.
3. I made a `ReviewListView` to render  a list of reviews
4. I updated `game_grid.html` to display the review form
5. I made a `game_reviews.html` to display a list of reviews that a game has

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work @danielngira !
Quite nice closing comment. Good job updating as you've worked! The kind of use of updates we want.
