### ISSUE TITLE
Create Placeholder Game Functionality

### ISSUE THREAD

**Issue by nugerhard** [uchicago-cs/chigame#266]
We are looking to create view(s) which stands in for a game, after a lobby has met its start conditions. This should be informative for future classes, to see at what points database instances are spun out: when the lobby, match, and player entities are created. 

Deliverables: a user should be able to click through some view, which subsequently tells the user whether they won or lost. Corresponding match entity should be created. For this task, because it is substantial, we are not concerned with linking this to the rest of the site yet: we just want to be able to access and walk through the game.

**Comment by nugerhard** [comment]
I have opted for a game in which you predict whether a coin lands on heads or tails. This is pretty straightforward to implement. There's also significant modularity, as any number of people could flip a coin simultaneously, so there aren't any real restriction on the number of people in the lobby.

**Comment by nugerhard** [comment]
Some observations: 

- We need to be able to make sure users aren't referencing the same game multiple times, i.e. they can't play multiple times. In some sense, the uniqueness constraint on matches takes care of this, but this is definitely not optimal. We can consider how to impose additional constraints in the integration phase. 

- I have been using /admin locally to see that the (match, player) records are being created correctly. How might we see these eventually from the main ChiGame site? Probably should be through user profiles.

**Comment by nugerhard** [comment]
Here's the PR: #267.
Here's the next associated issue: #268.

Again, this latter issue is concerned with hooking up our game to the lobby pages. Perhaps after this task is done, we might want to add a page on the wiki about how the game works.

**Comment by nugerhard** [comment]
Closing Commentary: The placeholder has been created, but it now needs to be integrated. Until it has been integrated, there could be some violations on uniqueness constraints in the database by playing a game multiple times from the same user.

**Comment by nugerhard** [comment]
Closing Comments (pt. 2): With pr #345, users should no longer be able to violate any uniqueness constraints in the database, nor be able to play a game multiple times. The page game_already_played.html is redirected to in the case of such bad behavior.

Nat: Built the placeholder game, namely the code (views, html) associated with the "placeholder-game" and "flip-result" urls. 
Chloe: Bugfixed code in the two corresponding pages html pages. Made suggestion for game_already_played.html.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Simple and well implemented coin flip game.
