### ISSUE TITLE
Integrate Placeholder Game

### ISSUE THREAD

**Issue by nugerhard** [uchicago-cs/chigame#269]
This task is concerned with getting the placeholder game to occur in a lobby that meets start conditions. This relies most directly on #266, our placeholder game, and #224, match start conditions. Some match behavior regarding how multiple user lobbies are created, needs to be ironed out as well.

**Comment by nugerhard** [comment]
Closing Comment: this task looked a little different from our initial description. It basically involved updating the views.py functions associated with "placeholder-game" and "flip-result". Essentially, we wanted to make sure that if a match already existed for the lobby, that a new match would not be created every time someone played the game. Moreover, we want the user to be able to return to the lobby page once they finished playing the game.

Chloe and Nat: Updated views.py with conditional match creation, and added button to allow for users to return to the lobby page from "flip-result".

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Lacks updates on a sizable issue, but otherwise good work.
