### ISSUE TITLE
update game model with reviews entity

### ISSUE THREAD

**Issue by danielngira** [uchicago-cs/chigame#271]
In this issue, we will update the game models in order to introduce a review entity. This is in response to issue #261 in which we will add a button to make reviews and view the reviews in the game detail page that was made in issue #40. This issue is consistent with the user stories that relate to users reviewing games which can be found here [https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories#rating-viewing-and-favoriting-games](url)

**Comment by danielngira** [comment]
Made new branch game-management/review-model

**Comment by danielngira** [comment]
Made a new Review entity in the models.py file to account for the reviews that a User leaves on a Game.

**Comment by danielngira** [comment]
This issue is closed as per PR #274. I added a Review model that allows a user to leave reviews and rate games. This issue will be useful in issue #261 where I will make views for reviews

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Thank you for your work @danielngira !
Appreciate you linking relevant issues and PR's!
