### ISSUE TITLE
(user profiles) Create user profile page that displays relevant information

### ISSUE THREAD

**Issue by 24raniwalar** [uchicago-cs/chigame#28]
Create a user profile pages that displays relevant personal information: display name, picture(if added). Profile page should only be accessible by the authenticated, active user and should be able to direct to a page to edit personal info if a user is viewing their own profile page. It should also include an Add Friend button if a user is viewing another user's profile.

**Comment by 24raniwalar** [comment]
User profiles should display name, profile picture, and maybe a username, among other user attributes.

**Comment by omarelkashef** [comment]
This will need to be updated to include achievements, friends, etc. when they are implemented

**Comment by omarelkashef** [comment]
added a view for users profile with an edit profile if it is the user's own profile and an Add Friend button otherwise.

**Comment by omarelkashef** [comment]
Closing statement: Added a user profile view with personal information such as the display name. My Profile in the nav bar directs to this new page. The profile page has an Add Friend button. allows users to edit their own profile page. The Add Friend button does not send any friend invitations; this is handeled by #29.

@omarelkashef  worked on displaying the information on the profile page
@24raniwalar  worked on adding the logic for the Add Friend button

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great first PR! Buttons looked good. For the future, make sure your closing comment specifies who did what task.
