### ISSUE TITLE
Implement a delete view for lobbies

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#280]
**Goal:** Users who created a lobby should be able to delete the same lobby in case it was created by mistake. We want to implement a Delete View of the CRUD pages to allow this to happen. We also need to figure out how to restrict access to this view to only the user who is the "host" of the lobby.

**Deliverables:**
- PR

**Comment by jiyeongchloe** [comment]
forked a branch called `matches/lobby-edit-delete`

**Comment by jiyeongchloe** [comment]
added delete views and debugged url issues
the view should be restricted to just the lobby creator now

**Comment by jiyeongchloe** [comment]
associated PR: [PR #282](https://github.com/uchicago-cs/chigame/pull/282)

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and task is finished.
We implemented edit and delete views that are only available to the lobby's host (nobody else can edit or delete). We also made sure to only display links to these on the frontend to the host.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Detailed goal and concise updates!
