### ISSUE TITLE
Implement an edit view for lobbies

### ISSUE THREAD

**Issue by jiyeongchloe** [uchicago-cs/chigame#281]
**Goal:** Users who created a lobby should be able to edit the same lobby in case they change their mind or inserted a wrong number by mistake when initially creating the lobby. We want to implement an Update View of the CRUD pages to allow this to happen. We also need to figure out how to restrict access to this view to only the user who is the "host" of the lobby.

**Deliverables:**
- PR

**Comment by jiyeongchloe** [comment]
forked a branch called `matches/lobby-edit-delete`

**Comment by jiyeongchloe** [comment]
added a framework for update view. We need to restrict access to just the host of the lobby

**Comment by jiyeongchloe** [comment]
added functions to check if the user requesting the change is the host and changed the display information in the detail page so that it displays the user email instead of username for now

**Comment by jiyeongchloe** [comment]
associated PR: [PR #282](https://github.com/uchicago-cs/chigame/pull/282)

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and task is finished.
We implemented edit and delete views that are only available to the lobby's host (nobody else can edit or delete). We also made sure to only display links to these on the frontend to the host.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Clear explanation of which users can edit lobbies.
