### ISSUE TITLE
Add pagination to game grid page

### ISSUE THREAD

**Issue by willcravitz** [uchicago-cs/chigame#286]
When we have a lot of games (like in the 50 or 500 games fixtures), they're displayed in an endless scroll on the game grid page. We want to add pagination to make it more manageable to browse games.

**Comment by willcravitz** [comment]
Following this guide (https://docs.djangoproject.com/en/4.2/topics/pagination/) and creating a new branch `game-management/pagination` to implement it

**Comment by willcravitz** [comment]
Used prebuilt Bootstrap pagination component described here (https://getbootstrap.com/docs/5.3/components/pagination/) and pushed initial working version.

There are a lot of options for doing pagination. You can have "Previous" and "Next" buttons, "First" and "Last" buttons, you need to choose how many page numbers to display, etc. I opted to use "First" and "Last" which appear disabled if you are on the first or last page, respectively. I also set it to display the page numbers of the previous and next pages if they exist. 

In the game list view, I set `paginate_by=20` to show 20 games per page, which was an arbitrary choice that seemed reasonable. Down the line we could allow the user to choose how many games they want to display per page.

**Comment by danielngira** [comment]
https://github.com/uchicago-cs/chigame/assets/81624602/c61ea7cf-c33f-4fa2-96eb-5c0227539fd0

The pagination works well for both the 500-game fixtures and the 50-game fixtures. I've been playing around with the code and I think the feature for allowing users to define how many games should go into a page is something we can implement later. Question about that though...Will it be implemented as a form in the game_grid view?

**Comment by willcravitz** [comment]
Good questions to look into @danielngira. I'm opening up issue #297 to address this. 

I think this feature is ready for PR.

**Comment by willcravitz** [comment]
Closing comments: This issue utilized the build in Django pagination https://docs.djangoproject.com/en/4.2/topics/pagination/ to split our games grid page in pages of 20 games and added a Bootstrap pagination component https://getbootstrap.com/docs/5.3/components/pagination/ to navigate between pages. 

Developer contributions:
@willcravitz added the initial pagination feature and styled it.
@danielngira tested/reviewed the feature and suggested a way to expand on it which will be implemented in #297.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Phenomenal job adding updates and providing the justification for your decisions (even if they're because "I arbitrarily chose it").

@danielngira Appreciate you using a screen-recording as well as thinking ahead to future work! 

Thank you both for your work
