### ISSUE TITLE
Allow admins to create new forums on the forum landing page

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#292]
# Goal
This issue seeks to allow creation of new forums, and this functionality should be made accessible on the forum landing page (`/forum`)

## Notes
- This functionality should only be available to admins
- Completion of this issue will require routing to a creation forum page

**Comment by bburgess19** [comment]
# Reason for reopening
PR #317 introduced a bug where the `board_base.html` couldn't be loaded because of a missing static tag. Because that PR is associated with this issue, we're not considering this issue complete until that problem is fixed.

To address this issue. I've opened #410, adding the `static` tag back into `board_base.html`.

**Comment by bburgess19** [comment]
# Closing comments
I created a admin-viewable button at `/forums` to allow creation of new forums. The button links to a barebones creation page, and upon successful form completion, redirects back to `/forums` where it can be viewed.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
