### ISSUE TITLE
(user) Edit profile page 

### ISSUE THREAD

**Issue by henrietta-k** [uchicago-cs/chigame#30]
Creating Edit page for the profile CRUD pages.

**Comment by ishiii-s** [comment]
Description: We added 7 different example users profiles all with passwords of either "test" or "foo", and usernames and emails based on their pk (e.g. pk = 1 --> "User 1")
Progress: We have submitted a pull request for the code, which is waiting review.

**Comment by AndrewM131** [comment]
Closing Statement: During Sprint 1, we realized edit profile page was already implemented, and we didn't need a PR for it.

**Comment by elizabethli31** [comment]
Issue Score: Unsatisfactory

Comments:
(updating this issue to unsatisfactory, as I realized this issue was not actually completed since it was a preexisting view)
