### ISSUE TITLE
Make search results unique and displayed as a grid

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#304]
This issue involves two relatively minor fixes. First, the search results should only return unique games i.e. no duplicates. Next, the search results should be displayed as a grid instead of the generic list view.

**Comment by ptlin25** [comment]
Branch `game-management/results-grid` created for this issue

**Comment by ptlin25** [comment]
This issue has been completed via PR #306. The `distinct()` method was added to remove duplicate games from the search results. The game search results also uses the grid view now instead of a basic list view, so it is consistent with the normal game browsing page.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! 
Thank you for the good closing comment and linking to the relevant PR!
