### ISSUE TITLE
Add the forum search bar to the search bar options dropdown in the nav

### ISSUE THREAD

**Issue by Benjoman12** [uchicago-cs/chigame#307]
The purpose of this task is to add the forums search bar to the search bar options dropdown found in the nav-bar. This will ensure that the forums can be searched even if a user is not on the forums part of the site.

**Comment by Benjoman12** [comment]
I've added the forum search bar to the search bar options in the dropdown menu in the nav-bar and submitted a pull request to merge it into dev.
* https://github.com/uchicago-cs/chigame/pull/309

**Comment by Benjoman12** [comment]
Closed after successfully merging and closing PR https://github.com/uchicago-cs/chigame/pull/309. Thanks to @joshuamonroe for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
