### ISSUE TITLE
Icon and Logo

### ISSUE THREAD

**Issue by frowenz** [uchicago-cs/chigame#308]
It would be nice to have a logo/icon as branding. The goal of this issue will be to document the process of creating a logo and the final output will be a pull request with a logo and icon in the static images folder.

**Comment by frowenz** [comment]
## Creation Process
1. I used DALL-E to create some initial images with the following prompt:

`A sleek minimalist logo for a UChicago student-created board game site, using two colors, with a design that merges a phoenix with the shape of a knight chess piece.`

2. I then combined these images in Photoshop and passed then through a Stable Diffusion img2img generator with the following prompt:

`(flat logo,: 3), (two color logo : 2), (sleek : 2), (minimalist : 2), (knight chess piece with a (phoenix : 4) head), (University of Chicago colors)`

3. I then used photoshop to make some finishing touches such as using `cutout` filter to remove gradients and noise .

The AI's were smart enough to use colors that corresponded with [UChicago's branding](https://news.uchicago.edu/sites/default/files/attachments/_uchicago.identity.guidelines.pdf) which I thought was very impressive.


![logo_evolution](https://github.com/uchicago-cs/chigame/assets/69015620/1c2a83df-678b-43cd-8c61-ef3f0da7fc33)

**Comment by frowenz** [comment]
Closing comment:

I created a logo using a combination of photoshop and generative AI. This logo was added to the navbar and as a favicon. Currently, all logo related files are in `src/static/images/logos` and the favicon is in `src/static/images/favicons`.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Thank you very much for posting the progress of your work as well as the details of what tools you used and how! 
Much much clearer than saying "I used generative AI to make this picture".

Consider your mark on chigame truly made :)

Thank you for your work.
