### ISSUE TITLE
(user profiles) create sample user profile page 

### ISSUE THREAD

**Issue by ishiii-s** [uchicago-cs/chigame#31]

**Comment by ishiii-s** [comment]
Closing Statement:
This task is done. Implemented fixture file with sample users, including an admin user.

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Good fixture that was super helpful for testing. This issue spanned sprint 1 and 2, and there's no description, so I'm giving it a satisfactory.
