### ISSUE TITLE
Integrate the forums advanced search option into the nav bar

### ISSUE THREAD

**Issue by Benjoman12** [uchicago-cs/chigame#310]
The aim of this issue is to incorporate the advance search option where the forum search option is available.

**Comment by Benjoman12** [comment]
Machina's advanced search function for forums has been implemented and only is visible on searching the forums and a corresponding pull request was submitted.

* https://github.com/uchicago-cs/chigame/pull/358

**Comment by Benjoman12** [comment]
Closed after successfully merging and closing PR https://github.com/uchicago-cs/chigame/pull/358. Thanks to @joshuamonroe for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
