### ISSUE TITLE
Get user detail endpoint to use username as slug in addition to primary key (`/api/users/<userID>` OR `/api/users/<username>`)

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#320]
**Goal:** In this issue, we want to allow users to access the Detail view of a `User` object using the user's `username` as a slug instead of always having to use the user's `id`. This way, it is easier for someone to use the API to get details of a specific user, as one does not need to know it's primary key in the model. 

We will support: `/api/users/<user_id>` AND `/api/users/<username>` to GET/PATCH/DELETE the Detail view of the `User` with the given `id` or `username`

**Comment by abrahmasandra** [comment]
Closing Comment: Successfully, completed the `slug` functionality to get the detail view of a `User`. Can now access the detail view going to endpoint: `/api/users/<user_id>` OR `/api/users/<username>`.

**Comment by abrahmasandra** [comment]
Note: Also enforce that the `username` is non-numeric in the database. This way, we know when the `slug` is a `user_id` or a `username` (e.g. a `username` cannot be "1234")

**Comment by majorsylvie** [comment]
Issue Score: Excellent
