### ISSUE TITLE
Match End Procedure: Make Lobby Unavailable at the End of a Match

### ISSUE THREAD

**Issue by ambr-lise** [uchicago-cs/chigame#322]
Goal: At the end of a match, the lobby which instantiated the match should be deleted. Any players remaining in the lobby should be removed, and the lobby should become inaccessible. The lobby should be moved to / marked as Closed.

Deliverables: [add description of intended behavior here -- fixtures to use when testing, links to use, etc.]

**Comment by nugerhard** [comment]
The extent this can be implemented for this sprint–which is, w.r.t. the placeholder game–has been implemented in PR #345. This exists in the views.py file, under the check_guess function: after the game is completed (i.e. player records have been created for all players), lobby.match_status is set to three.

**Comment by nugerhard** [comment]
Maybe we still need a way to filter out closed lobbies on our lobby list page. Should create that task in the backlog.

**Comment by nugerhard** [comment]
Closing Comments: After a match finishes, a user can still access lobby details page, but the only functionality still available to them (regardless of their status in the lobby) will be to return to the list of lobbies. This was included as part of PR #345.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Missing a label but otherwise looks good.
