### ISSUE TITLE
Prevent crashing behavior in Placeholder Game

### ISSUE THREAD

**Issue by nugerhard** [uchicago-cs/chigame#323]
This is the second half of the actual implementation task for the dummy game we constructed. Essentially, we initially built the game to simply crash if there was an integrity error in the database (e.g. if someone tried to play in a match twice and thus created two player records, or if two matches were created from the same lobby). This issue is meant to address that.

**Comment by nugerhard** [comment]
We now have an html page that the player is redirected to, if they attempt to play a match twice. This page has a redirection link to the lobby page.

**Comment by nugerhard** [comment]
We also now have the (sensible) feature that if two different players play a game associated to the same lobby, their player records contain the same match. Since match and lobby have a 1-1 relationship, this should obviously be the case. But in the initial implementation of the placeholder game, there was an integrity error when the second player attempted to play the game: one match was created each time someone played.

**Comment by nugerhard** [comment]
In general, with good integration into the lobby page, the user wouldn't get these errors prior to this issue. But in an effort to make the placeholder game a more complete piece of code, we added these guardrails.

**Comment by nugerhard** [comment]
Closing Comment: I identified the places which need to check whether a player and match entity have already been created, in order not to violate uniqueness constraints. I created a page that the user, in lieu of making such a violation, is redirected to ("game_already_played.html").

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice changes reflected in the PR for this issue.
