### ISSUE TITLE
Enable more robust search backend with realtime indexing

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#325]
Searching the forums with the default Haystack search backend in django-machina does not reliably return search results. According to the [Haystack docs](https://django-haystack.readthedocs.io/en/v2.7.0/tutorial.html#simple) this is not unexpected behavior for the very barebones 'simple' backend implementation, which is not recommended for use in production. To that end, the purpose of this issue is to enable the more robust 'whoosh' backend that is recommended in the [django-machina docs](https://django-machina.readthedocs.io/en/stable/getting_started.html#django-haystack-settings) as an alternative to the default.  Additionally, to alleviate the need to run `update_index` every time the forum content changes to make it searchable, Haystack's [realtime signal processor ](https://django-haystack.readthedocs.io/en/latest/signal_processors.html#realtime-realtimesignalprocessor) will also need to be activated.

**Comment by joshuamonroe** [comment]
I've installed the whoosh search backend with realtime indexing enabled and submitted a pull request to merge it into dev.
- #342

**Comment by Benjoman12** [comment]
Closed after merging and closing PR https://github.com/uchicago-cs/chigame/pull/342. Thanks to @joshuamonroe for writing the code for the PR and implementing the requested feedback.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
The title is too generic and could relate to other teams.
