### ISSUE TITLE
Creating Test Cases: Game GET API Endpoint  

### ISSUE THREAD

**Issue by giomhern** [uchicago-cs/chigame#327]
This issue pertains to the development of comprehensive test cases for the Game GET API Endpoint. The objective is to ensure that the endpoint reliably returns accurate game data under various scenarios.

**Comment by giomhern** [comment]
Closing this issue here! The Game factory now works great and passes all of the tests. As mentioned in the PR, issues in regard to mismatching object and data types have been resolved. 

Thanks to @giomhern for opening the issue and coding in the PR and @cuyakonwu for being an awesome reviewer!

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
While and update comment or two would be welcome, this is godo work.
Thank you for your closing comment and work!
