### ISSUE TITLE
(tournaments) create user stories for creating a tournament

### ISSUE THREAD

**Issue by Riyush** [uchicago-cs/chigame#33]
When a user wants to create a tournament, there needs to be a formal process for the user to initiate a tournament and specify tournament details like tournament players, the game being played, etc. We will create a user story that describes how a user interacts with our website to create a tournament. The user story should start when a user decides to start a tournament. The user story should end when the tournament has been created in the website.

**Comment by jb-01** [comment]
@Riyush

I've addressed your request and outlined a user story for the tournament creation process. It covers the journey from the user's decision to create a tournament up to the tournament's successful creation on the website. You can review the detailed user story in the new wiki page [here](https://github.com/uchicago-cs/chigame/wiki/Tournaments-~-User-Stories#user-stories-for-creating-a-tournament). Let me know if you have any feedback or adjustments needed!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good job! User stories were very comprehensive. I like the way they were divided into steps of the user flow along with the addition of alternative flows.
