### ISSUE TITLE
Researching how 3 public APIs manage authentication and access. Guides future creation and usage of APIs on Chigame

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#330]
**Goal**: Research several public APIs to get a strong reference on how larger code bases deal with giving access to APIs to others. This will allow the current API team of Chigame to see examples of how to model access and authentication of our current and future endpoints.

**Comment by cuyakonwu** [comment]
I will be looking into 3 public APIs with 3 different Authentication methods. Dota 2 has no Authentication method, Riot Games uses an APIkey and Steam uses OAth

**Comment by cuyakonwu** [comment]
[Dota 2](https://docs.opendota.com/) allows anyone to GET almost any information that is non-sensitive. Everything from any user's name and icon, to the statistics of any given champions in the game. With no authentication they reduce the amount of data that one can be provided as long as they assume it is non-harmful in the public domain

**Comment by cuyakonwu** [comment]
[Riot Games](https://developer.riotgames.com/) requires one to already have a riot account before accessing their API, you can then choose to view it on GitHub, Discord or Twitter after accepting their policies. You are then brought to their repo with instructions on how to use their API. You must access their API through the FastAPI app which give you an access token which is tied to every request you make, allowing them to track requests

**Comment by cuyakonwu** [comment]
[Steam](https://developer.valvesoftware.com/wiki/Steam_Web_API) uses a key as well to access data summarized as follows "All interfaces and method are self-documented through the ISteamWebAPIUtil/GetSupportedAPIList call. This can be found [here](http://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v0001/).

When passed a key=<your API key> parameter, GetSupportedAPIList will show all APIs that your key can access. Without it (as above), it only displays APIs that do not require an API key."

**Comment by cuyakonwu** [comment]
I believe Chigame would benefit the most from a system similar to steam when accessing data as Chigame would eventually become a similar product long-term. Being able to adjust access based on any given key would be beneficial in granting permissions with more specificity per user

**Comment by cuyakonwu** [comment]
This research has provided valuable insights into the authentication mechanisms of three prominent public APIs: Dota 2, Riot Games, and Steam. Each exhibits a distinct approach, from open access in Dota 2, Riot Games' requirement for a Riot account and token-based authentication, to Steam's key-based access with detailed self-documented interfaces.

**Key Takeaways:**
Dota 2's minimalistic, non-authenticated access emphasizes openness for non-sensitive data.
Riot Games mandates a Riot account, utilizing FastAPI for token-based access, enhancing security and tracking capabilities.
Steam's API key system, allowing controlled access with specific permissions, aligns with Chigame's potential long-term vision.

**Recommendation for Chigame:**
Considering Chigame's future evolution, a system akin to Steam's API key model seems particularly beneficial. It offers a balance between flexibility and control, allowing granular permission assignment for diverse user roles.

This research serves as a foundational reference for the Chigame API team, informing best practices and inspiring thoughtful decisions in the ongoing and future development of API endpoints.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
