### ISSUE TITLE
NotificationQuerySet.get_by_actor() calls a non-existent method 

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#333]
While working on #332, we discovered that  in NotificationQuerySet.get_by_actor(),  get() is used to retrieve a Notification and then is_not_deleted() is called on the return value of the get() which is a Notification object while is_not_deleted() is a method of NotificationQuerySet not Notification.

**Comment by omarelkashef** [comment]
Closing Statement: the bug is fixed by using the appropriate method and now it raises an exception if no notification matches the criteria. Tests were added to cover this logic.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice work making sure notifications work properly! Marking this as minor because it is a small bug fix.
