### ISSUE TITLE
Add Support for Pagination to API endpoints supporting List views 

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#347]
Summary: When getting a list of all `Game`, `User`, `Lobby`, etc. instances, the API request currently just returns a single list of all of the instances. This can get extremely clunky, especially if ChiGame eventually has thousands of games, as each API request for List View will return such a large amount of data. In order to fix this issue, most APIs implement pagination, where each page is a certain set amount of model instances, and the List view returned JSON is split up by these pages, making it easier to manage.

We will know this is done when:

Endpoint: `/api/games`, `/api/users`, `/api/lobbies` is doesn't return one massive JSON, but is split into pages of fixed size

**Comment by abrahmasandra** [comment]
Decided on a `PAGE_SIZE` of 10, as it seems to not be too large, but also contain enough information on each page.

**Comment by abrahmasandra** [comment]
Closing Comment:

Added support for Pagination for the all the currently implemented List views (`/api/games`, `/api/users`, `/api/lobbies`). We set the `PAGE_SIZE` to 10 for now, but this can be changed in the future if necessary.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Looks good, simple straightforward issue where you've added relevant closing comments as necessary.

Good work!
