### ISSUE TITLE
View list of your friends

### ISSUE THREAD

**Issue by 24raniwalar** [uchicago-cs/chigame#352]
In this issue, we hope to add a button to the "My Profile" section of a user's own profile that allows the user to see a list of their friends. Each item in the list should link to the friends' profile page so users may be able to remove friends.

**Comment by 24raniwalar** [comment]
Closing Statement: Users may now view their friends through a "Friends List" button that is only displayed to the user if they are logged in and on their own profile page. The list of friends contains information about the friends that links to the friends profile page.

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Would have liked to have seen some updates on the issue!
