### ISSUE TITLE
Add the option for bulk actions on Notifications

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#353]
In the current inbox page, users can only do an action one notification at a time and each time the page will refresh. We need to allow users to select multiple notifications and do the same action on all of them. Notifications should also be marked as read once they are clicked by a user.

**Comment by omarelkashef** [comment]
We will also be adding some logic to mark a notification as read once it is clicked which was missed in https://github.com/uchicago-cs/chigame/issues/125 per a suggestion by @elizabethli31. The Issue and PR descriptions has been edited to reflect that.

**Comment by 24raniwalar** [comment]
Closing Statement: Users may now select notifications by using a checkbox next to the notification and may choose to either delete all or mark all as read.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Cool functionality for the inbox - nice work!
