### ISSUE TITLE
Style All Search Bars

### ISSUE THREAD

**Issue by Benjoman12** [uchicago-cs/chigame#354]
Django-Machina's default search bar styling is much nicer then the search bar styling that currently exists in the project. This issue aims to look into if it's practical to apply the Django-Machina styling search bar styling to all search bars.

**Comment by Benjoman12** [comment]
After looking at how Django-Machina does its styling and looking into where that styling is coming from it is clear that it should be straight forward to implement that styling for the search bar in base.html.

**Comment by Benjoman12** [comment]
The Django Machina styling was implemented into the search bar in base.html and a corresponding pull request was submitted.

* https://github.com/uchicago-cs/chigame/pull/368

**Comment by Benjoman12** [comment]
Closed after successfully merging and closing PR https://github.com/uchicago-cs/chigame/pull/368. Thanks to @joshuamonroe for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
