### ISSUE TITLE
Fix search bar so that it correctly submits

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#355]
Currently, the search bar is broken; when a user tries to submit a query in the search bar, the search bar does nothing. This is due to the text input field being renamed from "query" to "query-input" and then back to "query" while the javascript uses "query-input". In order to fix this bug, the html element will have the id "query-input". This also necessitates changing the user search results view and the games search results view to use "query-input".

**Comment by ptlin25** [comment]
This issue fixed the search bar by changing references to the search bar's text input field from "query" to "query-input". This not only fixed the search bar but improves clarity.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Minor as this was a bugfix.
Thank you for providing a detailed summary of the bug!
