### ISSUE TITLE
Explore how to make default search box dependent on the current page

### ISSUE THREAD

**Issue by Benjoman12** [uchicago-cs/chigame#359]
This issue aims to explore how to make the default search box be dependent on the page.

**Comment by Benjoman12** [comment]
Checks were put into the current box item selection part of base.html and a corresponding pull request was submitted. 

* https://github.com/uchicago-cs/chigame/pull/368

**Comment by Benjoman12** [comment]
Closed after successfully merging and closing PR https://github.com/uchicago-cs/chigame/pull/368. Thanks to @joshuamonroe for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
