### ISSUE TITLE
Fix CSS for Like and Dislike Buttons in Forums

### ISSUE THREAD

**Issue by giomhern** [uchicago-cs/chigame#360]
# Problem
The like and dislike buttons in our forums are currently experiencing styling issues that affect their appearance. This issue needs to be addressed to ensure a better user experience.

## Goals ##

The implementation for this should in some way address styling in these respects
- [x] Color of the buttons
- [x] Shape of the buttons
- [ ] Have the vote count have different styling based on the user's vote
- [x] Placement of the buttons

**Comment by giomhern** [comment]
Adding a closing comment: 
This issue and PR were created to fix the styling for the vote buttons on our forum detail page. A user now knows that the button has been pressed due to the color filling for the icon. The counter is increased accordingly as well in correlation to a separate issue and PR #341.

Thanks to @giomhern for taking initiative and producing a nice, clean solution and to @joshuamonroe and @bburgess19 for coming in and providing feedback, and aiding in further code enhancements.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
