### ISSUE TITLE
(game management) User stories for unregistered users (Owen, Patrick, Will)

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chigame#37]
### User Stories for Unregistered Site Visitors

**Goal:** To formulate clear and comprehensive user stories that portray how unregistered users navigate game-related aspects of the platform.

**Motivation:** Considering how unregistered users interact with game-related features will inform developer requirements and the design of the user experience. 

**Open questions:**
1. Should we introduce a call-to-action (CTA) for account registration and if so, when?
2. Should unregistered users be allowed to play games?

**Comment by frowenz** [comment]
User Stories for Unregistered Site Visitors

Goal: To formulate clear and comprehensive user stories that portray how unregistered users navigate game-related aspects of the platform

Motivation: Considering how unregistered users interact with game-related features will inform developer requirements and the design of the user experience. 

Open questions:
1. Should we introduce a call-to-action (CTA) for account registration and if so, when?
2. Should unregistered users be allowed to play games?

**Comment by frowenz** [comment]
As a more advanced feature, we could also consider adding a walkthrough or tutorial for navigating game-related aspects of the site. This would also apply to first time users.

**Comment by frowenz** [comment]
User stories for unregistered users have been added to the [wiki](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories). 

In response to the question of whether "Should unregistered users be allowed to play games?", the current decision is No.

**Comment by ptlin25** [comment]
User stories for unregistered or logged out users are now on the [wiki](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories). All of us helped draft the user stories in a google doc, and Owen finalized the user stories and added them to the wiki page

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
Great job! I like how you specifically stated the goals and open questions in your summary.
