### ISSUE TITLE
Create API Endpoint: GET/POST List of Groups + Detail View of Groups

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#372]
**Goal**

Set up an endpoint that retrieves information about a list of ChiGame Groups from API, serialized in JSON. This will be done at url `api/groups/`, and can be accessed by ChiGame users as well as third-party websites. The games GET request would include a group name, group members, the user it was created by, and the date created. 

ENDPOINT 

`/api/groups`: Supports GET and POST requests in order to get a list of groups (and the corresponding information) as well as be able to create new groups using the API

We will know this is completed when the functionality above is working.

**Comment by abrahmasandra** [comment]
Also added Detail View of a specific group at endpoint `/api/groups/<group_id>`

**Comment by abrahmasandra** [comment]
Closing Comment: 

Created two views (the list view and detail view) for the `Group` model. Specifically, created the endpoint `/api/groups` for list view, supporting `GET`/`POST` HTTP requests. Created the endpoint `/api/groups/<group_id>` to get the detail view of a particular group from the given `group_id` (endpoint supports `GET`/`PATCH`/`DELETE` requests)

**Comment by majorsylvie** [comment]
Issue Score: Excellent
