### ISSUE TITLE
(game management) User stories related to saving and categorizing games (personal lists, ratings) (Ryan, Patrick, Owen)

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#38]
We need to draft user stories for how users can save and categorize games. These categories include favorited games, custom/personal lists, and ratings.

**Comment by frowenz** [comment]
A first pass of these user stories can be found at [wiki](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories#rating-viewing-and-favoriting-games).

**Comment by ptlin25** [comment]
User stories related to saving and categorizing games have been added to the [wiki](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories). Ryan, Owen, and I all contributed to drafting the user stories. Owen finalized the user stories and added them to the wiki page

**Comment by majorsylvie** [comment]
Issue Score: Excellent



Comments:
Nice job! The ability to add these lists is a very nice functionality to have in Chigame and y'all have written good user stories.
Appreciate the in progress comment about making a first pass.
