### ISSUE TITLE
(game management) Create updated game entity to include attributes we want to detail a game (game rules, title, difficulty, etc.)

### ISSUE THREAD

**Issue by willcravitz** [uchicago-cs/chigame#39]
There are several attributes of a game (rules, difficulty, average play time, etc.) that are not currently reflected in the `Game` model. We will write a new entity (to be used in a later ERD) that includes the attributes which will be stored in the db and accounts for those which we will potentially retrieve from a remote API.

**Comment by frowenz** [comment]
## Proposed Additions to the Game Model

Given the proposed integration of the [Board Game Geek API](https://github.com/uchicago-cs/chigame/issues/45#issuecomment-1782179661) to assist staff users with autofill capabilities when creating a new game, it's essential to align our attribute fields for compatibility. The BGG API also provides several useful categories which we should consider, one of which includes [mechanics](https://boardgamegeek.com/browse/boardgamemechanic). For further details, refer to [this wiki page](https://github.com/uchicago-cs/chigame/wiki/Games-~-BoardGameGeek-(BGG)-API).

**Current Game Model:**
```python
class Game(models.Model):
    """
    A game (Chess, Checkers, etc.)
    """

    name = models.TextField()
    description = models.TextField()
    min_players = models.PositiveIntegerField()
    max_players = models.PositiveIntegerField()
```

**Initial Additional Proposals for a game model:**
* Designer (usually one, but possibly many)
* Artists (likely many)
* Publisher (possibly many depending on the version)
* Year Published
* Game Thumbnail
* Playtime:
    * Minimum
    * Maximum
    * Expected
* Rules
* Suggested Age
* Complexity
* Popularity metrics:
    * Number of times played
    * Number of Favorites
* Corresponding BGG ID (could be useful for updating game's attributes) 

**Other considerations and open questions:**
- How do we handle rules?
    - Some Possible Options: 
        - Just text (probably simple and good for now)
        - Board Game Arena has an external wiki that they embed on their website. See [BGG Chess Rules](https://en.boardgamearena.com/gamepanel?game=chess)
        - Just link to the rulebook. This depends on things being online and may not capture nuances of online play. [Example](https://cdn.1j1ju.com/medias/88/21/c2-blood-rage-rulebook.pdf)
- How do we handle images? 
    - Some Options: serialize image or upload somewhere and link to the location.
- The richness of data in Board Game Geek, like internal popularity metrics, could be useful. However, it could be tricky to use if not every game on ChiGame is linked with a BGG game. 
- How do we manage different versions or expansions? 
- Should we include alternative names provided by BGG? For instance, Perudo has multiple well-known names. [See here](https://boardgamegeek.com/boardgame/45/perudo/credits)
- BGG's data sometimes raises questions. Take the "suggested player age" data, for example. Should we just use the mode as the recommended minimum age?
```xml
<poll name="suggested_playerage" title="User Suggested Player Age" totalvotes="530">
    <results>
        <result value="2" numvotes="1"/>
        <result value="3" numvotes="0"/>
        <result value="4" numvotes="2"/>
        <result value="5" numvotes="7"/>
        <result value="6" numvotes="53"/>
        <result value="8" numvotes="254"/>
        <result value="10" numvotes="166"/>
        <result value="12" numvotes="40"/>
        <result value="14" numvotes="4"/>
        <result value="16" numvotes="2"/>
        <result value="18" numvotes="1"/>
        <result value="21 and up" numvotes="0"/>
    </results>
</poll>
```
- We also have to figure out how to do relationships. For example, users favorite games and add games to lists.

**Comment by willcravitz** [comment]
@frowenz, thanks for raising all these really good points. I'll try to respond to a few things:

**On Initial Additional Proposals for a game model:**

- I'm not opposed to tracking the designer, artists, publisher, etc., but I think there is a distinction to be drawn between the original board game and the board game that you play on our site. We want to provide as much information as possible that stays directly relevant to whatever implementation of the game is on our site. There's a potential for a game designer to take creative liberty with something like the art design.
- For the same reason listed above, I think we should avoid using BGG ratings/popularity metrics, and track all of that internally. There could be a very popular board game that has a poor implementation on our site or an unpopular board game with a great version on our site. 
- I really like the idea of storing BGG id when applicable for updating info. We can also use this to link out to the BGG profile. 

**Other considerations and open questions:**

- Rules: I agree that we should stick with text based for now. It could be a nice future feature to offer developers a "Rules" page interface.
- Images: For many games we can link the BGG image which I assume is stored on their servers.
- Expansions and alternate names: I think we should avoid these as much as possible. They clog up a lot of the searches, so we might need some way to exclude them from the search results for admins. The API is very limited in its ability to do this. 


A lot of these issues are things I expect we'll sort out when we flesh out the models to add rating, categorizing, game + user interactions, etc.

**Comment by danielngira** [comment]
- I agree with both @frowenz and @willcravitz in that the rules should be text-based for now. It would be good if they had a page of their own. On the page, we can link to the rulebook in case the player wants an in-depth reading.
-  We can use the data from the ratings to predict the popularity of a movie so is that a feature we will implement later?
- When making a view for the game publishers, I realized the games have large numbers of publishers. Maybe we can implement this in a similar way to the course descriptions in Uchicago's college catalog where clicking on the course provides us with its description. In our cases clicking on publishers will provide a small pop-up window with the list of publishers.

![Image](https://github.com/uchicago-cs/chigame/assets/81624602/d8a19498-7c0c-43fa-ba38-db4559123ef0)

In #46 we have made a page that has the following:

1. game thumbnail
2. year published
3. playtime
4. game publishers
5. game description

- We will add more information that we find to be necessary.

**Comment by willcravitz** [comment]
Reopening to add a closing statement per @fkbad's request

**Comment by willcravitz** [comment]
We provided a list of several new attributes that we believe should be implemented in the next update of the Game model.

Developer contributions:
@frowenz did the bulk of the work by listing the current Game model to show its limitations, suggesting several new attributes we could add, and raising several considerations that come along with these new attributes.
I did my best to respond to some of these considerations to help narrow down our attribute list.
@danielngira responded to these considerations and offered a UI solution for listing publishers. He also implemented some of the new attributes on our bgg api sample page in issue #46 to give a sense of what they'd look like on the page.

**Comment by majorsylvie** [comment]
Issue Score: Excellent



Comments:
Happy to see all of you writing follow up statements! 
Thank you for adding the developer contributions to the closing comment @willcravitz 

Thank you to all of you for adding extra formatting in the form of code blocks, headers, lists, and images to your update comments, makes them more organized and easier to read.

Keep going!
