### ISSUE TITLE
(game management) Create Individual Game Detail View and Template Page (Patrick, Ryan)

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#40]
Add detail template page for individual games. This page will show the name of the game, min and max number of players, game rules, and other game attributes specified in issue #39. A corresponding Django view must also be created to display the game detail page

**Comment by rakrusch** [comment]
Created branch game-management/game-detail for this issue, as well as pull request #71

**Comment by rakrusch** [comment]
Updated pull request per feedback. Updates include: adding links back and forth between game list and game detail pages, extended game detail page template from base.html, removed code for registering models (to be completed in separate issue)

**Comment by ptlin25** [comment]
Completed as of #71, basic detail page for each game has been added 

Work done by each assignee:
Ryan: coded the detail view and template
Patrick: general feedback and basic review before pull request

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
Great job y'all!
I appreciate y'all using issue/PR numbers to directly associate this issue with related issues and PRs.
Thank you for including the closing comment with the developer contributions.
