### ISSUE TITLE
(game management) Create edit / create views and templates for Games (Patrick, Will, Ryan)

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#41]
Need to add an edit view and a create view for Games that allows Game entities to be updated/modified or created from new. We must also add the corresponding templates for the edit and create views.

**Comment by ptlin25** [comment]
Created branch game-management/edit-create-views for this issue

**Comment by ptlin25** [comment]
We will have to update this view once we finalize our Game entity with updated attributes

**Comment by ptlin25** [comment]
Created basic edit and create views for Games

**Comment by ptlin25** [comment]
Addressed feedback from pull request review and resolved merge conflicts

**Comment by ptlin25** [comment]
Completed via #72. A basic edit and create view have been completed for the Game model. These views will have to be updated when we add additional attributes to the game model in #92.
Distribution of work:
Patrick: coding the views
Ryan and Will: feedback and advice

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Straightforward and done well! 
Thank you for linking relevant issues and pull requests as well as providing developer contributions.

Overall, I would ask for more descriptive updates, though for this issue I can see why there wouldn't be too much to update on given that the creation of direct templates for games has been made fortunately simple by Django.

Reminder that this format of issue title is now deprecated and for any new issues I will not grade them if they have `(team name)` and/or `(assignees)` in the title.
