### ISSUE TITLE
(game management) Register Game model with Admin page (and add more features?) (Patrick)

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#42]
The models in games must be registered with the Admin page before the models can be utilized and populated

**Comment by ptlin25** [comment]
Created new branch (game-management/register-models) for this issue

**Comment by ptlin25** [comment]
Added code to chigame/games/admin.py to register all models in games/models and pushed changes to GitHub

**Comment by majorsylvie** [comment]
As of now, you're registering the models via a for loop. 
I want you do register the models individually, since this way we will have more control over the customization features of each model.

**Comment by majorsylvie** [comment]
https://docs.djangoproject.com/en/4.2/ref/contrib/admin/

https://realpython.com/customize-django-admin-python/

![Image](https://github.com/uchicago-cs/chigame/assets/86740254/cf4e6c46-c63e-4e4a-9982-9c6be5917513)

As of now, your code doesn't have the names of models displayed in the admin interface. Please add an appropriate `__str__` method to the `Game` model such that the admin interface is more readable/useable. 

Then you can check out the above links to see how you can use the admin interface to customize your models

**Comment by ptlin25** [comment]
I added a `__str__` method to the `Game` model and customized the `Game` model in the admin interface to display the name of the game, minimum number of players, and maximum number of players. It is now possible to sort by these 3 attributes and also search by the name.

**Comment by ptlin25** [comment]
Complete as of PR #69, but improvements can be made to the admin interface's search feature

**Comment by majorsylvie** [comment]
Issue Score: Excellent



Comments:
I'm upgrading this from a minor issue since the back and forth and extra display features is enough for this to be a full issue.

Great job taking feedback, making an appropriate PR, and doing proper updating comments as work has progressed.
