### ISSUE TITLE
(game management) Research into BoardGameGeek API (file with endpoints, what info is in it, what we care about) (Will, Daniel)

### ISSUE THREAD

**Issue by willcravitz** [uchicago-cs/chigame#45]
For issue #39, there are several pieces of information about board games we want to display that are made available by the BoardGameGeek remote API. We need to research what data is available for access and what endpoints should be used to access that data. We will produce documentation with this information, and a sample page using the API in issue #46.

**Comment by willcravitz** [comment]
A few questions that need to be decided:

**When and where do we make the API call?**
1. Should it be done in JS on the frontend when a game page is loaded?
Pros: Information will always be up to date, no data modeling for storing game info
Cons: Need to make api call on every reload, could slow the site down

2. Should we make the call on the backend to get information when a game is created, then store everything in the DB?
Pros: We have ability to edit the game info, don't have to make api call to load game page
Cons: Storing extra info in DB, might get out of sync with most recent BGG data

**Should we use the official [BGG XML API v2](https://boardgamegeek.com/wiki/page/BGG_XML_API2) or an open-source [python](https://lcosmin.github.io/boardgamegeek/)/[JSON](https://bgg-json.azurewebsites.net) wrapper someone else has developed?**
The official API is more stable, maintained by BGG, production quality code, etc. The wrappers will be easier for us to work with (JSON over XML), and they look fairly well-documented.

**Comment by willcravitz** [comment]
New idea for using the API:
When an admin creates a game, they begin to type in the title of the game in some field. Then we can call the BGG api and present a bunch of auto-fill options for that title which correspond to listed game titles on BGG. If the admin doesn’t select one of these options, they’ll just proceed to manually enter the rest of the game info in the remaining fields. If they do select one of the options, then we make a call to BGG to get the info for that game, and we autofill the rest of the fields (description, image, min/max players, play time, etc.). The admin still has an opportunity to edit all of these fields before they officially create the game.

**Comment by willcravitz** [comment]
Added a [page to the wiki](https://github.com/uchicago-cs/chigame/wiki/Games-~-BoardGameGeek-(BGG)-API) to list a few of the most important endpoints and provide basic info on handling the XML response. We plan to use the BGG API to make it easier for admins to add games by autofilling game info. We still need to decide whether we should make the api calls on the frontend or do it through django and feed info into the templates.

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
Great job! That wiki page is very actionable, clear, and well formatted.
With regards to response time, it is not horrible to have API calls happen on reload.  There is also the ability to cache in django: https://docs.djangoproject.com/en/4.2/topics/cache/

However, I would recommend to not worry about API performance much right now since Chigame is a small repo, and we don't need to prematurely optimize around hypothetical performance loss.
