### ISSUE TITLE
Create API endpoint: GET List of Games

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#48]
**Goal**

Set up an endpoint that retrieves information about a list of ChiGame Games from API, serialized in JSON. This will be done at url `api/games/`, and can be accessed by ChiGame users as well as third-party websites. The games GET request would include how many players (min_players, max_players), the name of the game, the description, and other attributes.

ENDPOINT 

`/api/games`: Supports GET and POST requests in order to get a list of games (and the corresponding information) as well as be able to create new games using the API

We will know this is completed when the functionality above is working.

**Comment by abrahmasandra** [comment]
Added Game List view building off of the Django REST framework. Added a Game Serializer class to serializers.py file, as well as the corresponding URL (/api/games) and view (GameListView) in urls.py and views.py respectively

**Comment by majorsylvie** [comment]
when trying to run the code on the `apis/game-endpoints` branch, I get the following error: 

```python
    app_module = import_module(app_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'api'
```

@abrahmasandra are you able to actually run the server and open the endpoint with your current code?

**Comment by abrahmasandra** [comment]
I had accidentally forgotten to push the latest changes to Github (I had to add the url to the urls.py of the main project). Now, I pushed the latest code and it should be working now. The urls for the api are /api/games and /api/games/<int:pk>. I have tested locally and it is working.

**Comment by abrahmasandra** [comment]
GET Games working! Endpoint is /api/games and supports GET and POST requests to get a list of all the games and create new games

**Comment by abrahmasandra** [comment]
Closing statement: Implemented the Game List and Detail views of the Chigame API under the endpoints `/api/games` and `api/games/<int:id>` respectively

@abrahmasandra: created the endpoints

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job! Thank you for nailing the combination of descriptive title, summary, updates, and closing comment.

Particularly appreciate you detailing what endpoint should be created as the goal.
