### ISSUE TITLE
Create API endpoint: GET details about individual games

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#50]
**Goal**

Set up an endpoint that retrieves information about the details of a specific game from API, serialized in JSON. This will be done at url `api/games/<int:GameID>`, and can be accessed by ChiGame users as well as third-party websites. The GET request would include information about the specific game with the primary key of `GameID` (information such as name, description, max_players, etc.). This endpoint would also support PATCH/DELETE requests to change the details of a specific game and delete games from the database.

ENDPOINT

`/api/games/<int:GameID>`: Supports GET/PATCH/DELETE requests to get the details of a specific game, change the details of a specific game, and delete a specific game from the database, respectively.

We will know this issue is completed if this functionality works as described above.

**Comment by abrahmasandra** [comment]
Added Game Detail view to see the information about an individual game, building off of the Django REST framework. Added a Game Serializer class to serializers.py file, as well as the corresponding URL (/api/games/<int:pk>) and view (GameDetailView) in urls.py and views.py respectively

**Comment by abrahmasandra** [comment]
DETAIL view working!! Can get the detail view of games at the endpoint of /api/games/<int:pk> where pk is the primary key of the game in the Game model. This supports GET requests to get details for a specific game, as well as PATCH and DELETE requests to tweak the information about a game and delete the game as well

**Comment by abrahmasandra** [comment]
Would be useful to instead of using the primary key of the game, maybe use the **slugs** so that we can replace the primary key in the API endpoints with the game title, or another unique field that is more human readable

**Comment by abrahmasandra** [comment]
Closing statement: Implemented the Game List and Detail views of the Chigame API under the endpoints /api/games and api/games/<int:id> respectively

@abrahmasandra: created the endpoints

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job actually adding updates as you've worked.
Thank you for specifying the endpoints you created.

Its good to see descriptions for tasks get more descriptive!

Keep going!
