### ISSUE TITLE
Create API endpoint: GET/POST list of Lobbies (URL: /api/lobbies/)

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#52]
**Goal**

Set up an endpoint that retrieves information about a list of ChiGame lobbies from API, serialized in JSON. This will be done at url "api/lobbies/", and can be accessed by ChiGame users as well as third-party websites. The lobbies get request would include how many players, what game is being played (including whether its tournament or match), and availability (private or public lobby, etc.) for all lobbies.

ENDPOINT: `/api/lobbies`: Supports `GET` and `POST` requests in order to get a list of lobbies (and the corresponding information) as well as be able to create new lobbies using the API

**Comment by abrahmasandra** [comment]
Note: along with the list view of the lobbies, I also added the detail view, as this was a part of another issue (#51).

Added API Endpoints:

`api/lobbies/`: GET/POST new lobby objects
`api/lobbies/<int:pk>`: GET/PATCH/DELETE specific lobby objects

Implementation is very similar to the Game list/detail views. I specifically edited the URLs, as well as created two new Views (List + Detail views for lobbies), and created a `LobbySerializer` class to serialize and deserialize Lobby objects

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Thank you for specifying the endpoints created, good job using the markdown formatting for better readability!
