### ISSUE TITLE
Write user stories for forum groups

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#59]
This issue involves creating user stories to better understand how users may interact with groups and tournaments on the chigame forum. These stories should cover scenarios including joining and participating in public communities, creating and participating in private groups, and organizing and participating in tournament related communities. Through these stories, we should gain a clear picture of what our users need and expect when it comes to group related interactions on the forum.

**Comment by bburgess19** [comment]
## User Stories
- Arthur is an admin who creates a new public discussion open to anyone for reading and registered users for posting.
- Stacy is a registered user visiting a FAQ forum. She creates a new post in this forum with a title and body.
- DJ is a registered user. He visits the forums page and creates a new private forum called "FooBar is the best" which is only visible to those users who DJ invites.
- When viewing the pane to invite users to his forum, DJ is shown his list of friends alongside a search bar to search for any user by user name.
- Rachel is a registered user interested in following a game tournament. When viewing the overview page of the tournament, there is a "discussion" tab she clicks on to show conversations discussing the overall happenings of the event.
- When Rachel clicks on one of the matches displayed in the tournament, she further navigates to a discussion tab related specifically to that match.
- When a match is created, a corresponding forum is created and associated to that match.
- When a new game is posted, "General" and "Tips and Tricks" forums are made alongside it.

@joshuamonroe let me know any ideas you have for revisions/features.

**Comment by joshuamonroe** [comment]
- ~~Arthur is an admin who creates a new public discussion open to anyone for reading and registered users for posting.~~
  - This story seems more appropriate as an admin story.
- ~~Stacy is a registered user visiting a FAQ forum. She creates a new post in this forum with a title and body.~~
  - This story seems more appropriate as a registered user story.
- DJ is a registered user. He visits the forums page and creates a new private forum called "FooBar is the best" which is only visible to those users who DJ invites.
  - Should we allow any registered user to create arbitrary forums? It might be better, given the context (i.e. we aren’t making Reddit) to limit forum creation to automated events, such as addition of a new game to the platform, or to admins. An alternative story might go something like this:
  - DJ is a registered user. He creates a new group called “The FooBarbarians” and invites his friends to join. As a group admin, he is given the option to activate a private forum for the group. Upon doing so, the private forum is created automatically and the members of the group are granted access and notified of its activation.
- When viewing the pane to invite users to his forum, DJ is shown his list of friends alongside a search bar to search for any user by user name.
  - I think this story makes sense given the original context of the previous story but is out of scope if private forums are tied to existing groups on the platform broadly.
- Rachel is a registered user interested in following a game tournament. When viewing the overview page of the tournament, there is a "discussion" tab she clicks on to show conversations discussing the overall happenings of the event.
  - This one looks great!
- When Rachel clicks on one of the matches displayed in the tournament, she further navigates to a discussion tab related specifically to that match.
  - Looks good, but I think we can associate a match with just a single forum thread. With that in mind, here is a slightly revised version of this story:
  - When Rachel clicks on one of the matches displayed in the tournament, she further navigates to a discussion tab related specifically to that match which displays a forum thread associated with the match.
- When a match is created, a corresponding forum is created and associated to that match.
  - This story could be fleshed out a bit. A more detailed version might look something like this:
  - Max, a forum moderator, creates an official tournament. When he does so, a corresponding forum is automatically created and associated with the tournament. Now, each time a match is scheduled in the tournament, a thread is automatically created and associated with the match.
- When a new game is posted, "General" and "Tips and Tricks" forums are made alongside it.
  - In my mind, although I think it makes sense at the top level to have subforums dedicated to topics like these, I think it makes more sense at level of individual games to simply have a “Games” category with each a game having a single subforum within that category, with more granular discussions organized at the thread level. With all that in mind, here are two alternative stories:
  - A new game called is added to the chigame platform by the site admins. This event causes a subforum to be automatically created for the game in the “Games” category of the forum. Registered users can now create new threads discussing a variety of topics related to the game.
  - Max, a forum admin, notices that users have been using the “General” forum to ask for help with technical issues a lot lately. To help user more easily see other types of topics in “General” and also easily find help for their technical issues, he creates a new public forum called “Technical Help” to contain this type of discussion.

Overall some good work here, but I think we definitely have some room to circle back and flesh out some additional group related stories in the future. If there aren’t any objections to these revisions or additional revisions to make, let’s go ahead and get the revised stories pushed to the wiki.

**Comment by majorsylvie** [comment]
The big thing that stands out to me across the user stories is what feels like a lack of precision with your nouns.

What are:
- forums page
  - is this a home page? are forums on the forum page?

- tournament/match "overview page"
  - is this on the forum? or is this a page made by the tournaments team that we get to put a link on

- a forum 
  - eg:
    - tournament forum
    - match forum
    - private forum
  - are these distinct? are posts made on forums? 
- conversations
  - "conversations discussing the overall happenings"
  - what are these? are these replies in a one "forum" for a tournament? 
    - or is the tournament some kind of grouping of "conversations", "posts", "forums" etc...

then on Gio's registered user stories #62 , the language of "threads" "discussion" and "posts".
So putting all these user stories together is going to be messy because it's hard to tell which of these stories are referring to the same "thing".

I would highly encourage all of you @bburgess19 @joshuamonroe @giomhern to standardize your nouns across user stories. 

Y'all are doing a great job being thorough in your user stories, keep going!

**Comment by joshuamonroe** [comment]
@majorsylvie I've created issue #123 to address your feedback regarding the lack of standardization in our terminology across the user stories. Furthermore, I've updated the group stories to align with the proposed terminology and address your feedback.

@bburgess19 If there aren't any objections, let's go ahead and upload these stories to the wiki and close this issue. If there end up being any revisions to proposed terminology, we can make the necessary updates to the wiki as part of that process.

* DJ is a registered user. He creates a new group called “The FooBarbarians” and invites his friends to join. As a group admin, he is given the option to activate a private subforum for the group. Upon doing so, the private subforum is created automatically and the members of the group are granted access and notified of its activation.
* Rachel is a registered user interested in following a game tournament. When viewing the overview page of the tournament on the main chigame platform, there is a "discussion" link that takes her to the tournament’s subforum where she can create a post in a new thread or reply to someone else’s post an existing thread.
* When Rachel clicks on one of the matches displayed in the tournament, she is given the option click on a discussion link related specifically to that match which takes her to a thread associated with the match in the tournament’s subforum.
* Max, a chigame admin, creates an official tournament. When he does so, a corresponding subforum is automatically created and associated with the tournament. Now, each time a match is scheduled in the tournament, a thread is automatically created and associated with the match.
* A new game called is added to the chigame platform by a chigame admin. This event causes a subforum to be automatically created for the game in the “Games” category of the forum. Registered users can now create new threads discussing a variety of topics related to the game.
* Max, a forum admin, notices that users have been using the “General” subforum to ask for help with technical issues a lot lately. To help other types of topics to remain visible to users in “General”, while also enabling them to more easily find help for their technical issues, he creates a new public subforum called “Technical Help” to contain this type of discussion.

**Comment by joshuamonroe** [comment]
I've added the revised user stories from my previous comment to the [wiki](https://github.com/uchicago-cs/chigame/wiki/Forums-~-User-Stories) and closing this issue now. Thanks @bburgess19 for getting these drafted.

**Comment by majorsylvie** [comment]
Issue Score: Excellent



Comments:
This issue did last two sprints. In the future when we have a holdover task that is almost done, please finish it ASAP after the team meeting for it to be considered part of the previous sprint.

Great job being more specific in your nouns for the updated user stories, these feel much nicer now. 

Great collaborative work, keep going!
