### ISSUE TITLE
Look into existing Django libraries for forum implementations

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#61]
This issue aims to explore available Django libraries suitable for integrating a forum feature into the chigame platform. Our exploration will help identify libraries that can facilitate smooth implementation of general, game, support, and event related communities, along with features such as thread creation, commenting, liking, and moderation. An analysis of each library's suitability to our use case and ease of integration is sought to ensure a robust forum functionality. The outcome should provide a shortlist of promising libraries, from which we can select one to begin integrating into the project.

**Comment by joshuamonroe** [comment]
My initial research into this issue has turned up [django-machina](https://github.com/ellmetha/django-machina) and [Misago](https://github.com/rafalp/misago) as promising options worth reviewing. These two seem to be the most fully featured and actively maintained libraries with the potential to provide the forum functionality that we are looking for.

Two, somewhat less well maintained, alternatives that may also be worth considering are [PyBBM](https://github.com/hovel/pybbm) and [Spirit](https://github.com/nitely/Spirit).

Next steps will be to perform a more comprehensive assessment of each project and a comparison of those that are found to be viable options.

**Comment by giomhern** [comment]
It certainly looks django-machina is updated more frequently than any others,  given the recent commits. It also has good docs and extensibility for the implementation in current projects. On that same note PyBBM is looking good as for reference components (good docs and extensibility as well), but less features from what it seems. 

Also, not directly a GitHub for the above, but I found this [chess-game forum](https://github.com/YuriiDorosh/chess-forum) that is updated quite recently, but actually seems more like a personal project, so probably not the best thing to reference. 

Aside from that, researching leads me to the same ones, and I think we can probably clone some repos locally that use either to see which one provides a better both user and development experience, and how able we are to make adequate and significant changes for our usage.

**Comment by Benjoman12** [comment]
I would urge us to look at using Django-machina or Misago. Django-machina is far more extensive than Misago so it would be fantastic to implement at a high level in the project but, since we only have control over the forum Misago may be better to implement due to its very prebuilt nature. I would suggest that we spin up instances of both and delve into implementation.

**Comment by joshuamonroe** [comment]
As discussed in the team meeting, we are in agreement that we should move forward with further testing and assessment of both [django-machina](https://github.com/ellmetha/django-machina) and [Misago](https://github.com/rafalp/misago). To that end, issues #99 and #100 have been opened to further assess each of these libraries and I am closing this issue.

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
Great job on this y'all! This is a great example of a well done preliminary research issue.
Particularly good job including links, having multiple people participate, and writing a comprehensive closing comment that links relevant next-step-issues.
