### ISSUE TITLE
(game management) Create Game List View and Template (Patrick, Ryan)

### ISSUE THREAD

**Issue by ptlin25** [uchicago-cs/chigame#63]
Need to create a list view and corresponding html template for Games. The list view should show all the Games that have been added to ChiGame.

**Comment by ptlin25** [comment]
Created branch game-management/game-list

**Comment by ptlin25** [comment]
Created initial migration for games, added Game list view, url, and template

**Comment by ptlin25** [comment]
List view for Games has been created as of PR #67.

Work done by each assignee:
Patrick: created initial migrations, added code to create Game List View
Ryan: general feedback/review before official pull request review

**Comment by majorsylvie** [comment]
Issue Score: **Excellent**

Comments:
Great Job! 

This issue is a great example of a simple task completed through Agile!
Congrats on being the first PR into chigame :)
