### ISSUE TITLE
(matches) Create user stories for match creation, joining a lobby, and match instantiation

### ISSUE THREAD

**Issue by nugerhard** [uchicago-cs/chigame#64]
**Goal:** we imagine there is a pipeline from a user simply clicking around on the website, to a user actually being in a match. At a high level, this pipeline is (Create a Match)* -> (Join a Lobby) -> (Conditions for match beginning has been met) -> (Match Begins). *Only for person who creates the match. 

**Deliverables:** User story for person who creates a match, user story for person who joins a lobby (logged-in and otherwise), user story for person in a lobby.

**Comment by nugerhard** [comment]
Incl: What do things look like when a user is already in a match vs. not?

**Comment by jiyeongchloe** [comment]
Created a wiki page (Matches ~ User Stories) to document user stories

**Comment by jiyeongchloe** [comment]
Should (Join/Create a Lobby) be first in the pipeline? Match has a foreign key for Lobby, which makes me think we need a lobby before creating a match. Perhaps (Create a Match) should be named (Choose a game)?

(Choose a Game) -> (Join/Create a Lobby for that Game) -> (Conditions for match beginning have been met) -> (Create a Match) -> (Match Begins)

**Comment by nugerhard** [comment]
@jiyeongchloe: yes, I think you are correct. I think this points to a semantic issue that we have to be aware of: referring to match as an entity in our database, and to match as a general description of an instance of a game played on the website. I will try to avoid using match in the second sense for clarity. 

Users should probably not be able to create matches themselves. Only indirectly–by creating a lobby, and then subsequently joining a match–could a user "create" a match. Currently working on user stories to describe this.

**Comment by nugerhard** [comment]
New user stories added to [matches wiki](https://github.com/uchicago-cs/chigame/wiki/Matches-~-User-Stories). The subcategories I ended up going with are (Create a Lobby) -> (Find/Join a Lobby) -> (In the Lobby/Match Instantiation), which have some sequentiality. Let me know what you think of them when you get a chance. Once you have a look and supplement as needed, I think this task is basically done.

**Comment by jiyeongchloe** [comment]
Added user stories for spectators.
Also, what do you think about allowing the lobby-host the choice to extend the time-to-start timer instead of automatically redirecting users to the aggregate page if the timer runs out without having sufficient users in the lobby?
We might also want to think about whether users can play multiple matches (one after another) in the same lobby (might make it easier if they want to play again with the same group of people or they want to play under 'best out of 3').

**Comment by jiyeongchloe** [comment]
In-Person meeting notes:
- one match per lobby
- no extension on timer allowed

changes updated in wiki

**Comment by jiyeongchloe** [comment]
Issue is basically done; We've updated the [wiki](https://github.com/uchicago-cs/chigame/issues/64#issuecomment-1786076214) with user stories that address lobby creation, lobby spectating, lobby joining, and match starts.

Nat: wrote user stories for (Create a Lobby) -> (Find/Join a Lobby) -> (In the Lobby/Match Instantiation) for logged-in and logged-out players
Chloe: wrote user stories for (Find/Join a Lobby) -> (In the Lobby/Match Instantiation) for logged-in and logged-out spectators

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good job! Again, super detailed! Spectating might be a little too out of scope for this year, but can Dan spectate if he isn't logged in? Also, you could possibly add some more context on lobbies for friends only. There are a few user stories that mention making lobbies for a match with their friends, but can other people join the lobby regardless of friend status? Is this something you want to restrict with options like "everyone", "friends only", etc?
