### ISSUE TITLE
(matches) create view for allowing users to join a lobby (Lucien and Moses)

### ISSUE THREAD

**Issue by xylucien** [uchicago-cs/chigame#65]
Goal: implement a lobby list page that display all join-able lobbies to any user. When clicking on a lobby title, user should be directed to the detail page of that lobby.

**Comment by xylucien** [comment]
added an html file for display; next step will be implementing the corresponding function in views.py and adding the URL to urls.py.

**Comment by xylucien** [comment]
closing statement: task done. Used a customized table HTML element instead of the default listview for this page because there are multiple attributes to display for an entry. Next step may include frontend beautification.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Similar comments as the issue #66 - good work but try to complete issues within one sprint!
