### ISSUE TITLE
(user profiles) Search for Users

### ISSUE THREAD

**Issue by 24raniwalar** [uchicago-cs/chigame#68]
Create a search bar and search results page with the necessary backend components such that users can search for other users in the navigation bar by looking up emails (May edit to include search by username if we decide to edit the User model to include usernames)

**Comment by omarelkashef** [comment]
This issue depends on #29 and #28 to be able to send request and direct to profile pages from the search results page. For now, the search result page redirects to user:detail which needs to change to a profile page view after #28 is implemented and add friend button send friend invitations.

**Comment by omarelkashef** [comment]
This issue concerns the whole app so we are collaborating with the games team to handle it.

**Comment by omarelkashef** [comment]
Closing statement: we met with the games team and decided to work together on this feature. We will create two issues (for not) to handle the searching functionality in the app. Each issue will have members from both teams working on it. The games team documented their progress in #89 
@omarelkashef met with the games team to devise an initial plan for collaboration and draft for what work needs to be done
@24raniwalar implemented a search bar that redirects to a profile given the email of a user.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work communicating with game management and also updating them on matches' need for a search bar too. It looks like most of the documentation and research is on the other team's issue. Also since you guys are breaking this down into more issues, I'm labeling this one as minor.
