### ISSUE TITLE
(matches) create user stories for match ending procedures

### ISSUE THREAD

**Issue by nugerhard** [uchicago-cs/chigame#70]
**Goal:** we are looking to clarify what happens to a match, after it finishes. What sort of information about the match remains accessible to the user? Where do they access this information? What sort of statistics are tied back to a user's profile, based on their performance in the match? What happens when a user desynchronizes from the match, (i.e. when they disconnect from the match?

**Deliverables:** User story for someone who finishes a match (for a win and a loss), user story for someone who wants to remember what happens in a previous match, user story for someone who disconnects from a match.

**Comment by jiyeongchloe** [comment]
Created a wiki page ([Matches ~ User Stories](https://github.com/uchicago-cs/chigame/wiki/Matches-~-User-Stories)) to document user stories

*edited to include hyperlink

**Comment by jiyeongchloe** [comment]
Added user stories for a general match-ending procedure

came up with stories depending on whether we want to allow multiple sequential games per lobby or limit it to one match per lobby; we can delete one or the other once we decide what we want to allow.

**Comment by ambr-lise** [comment]
Added user stories for what info to track after matches have ended. Still have to add user stories for Magic: The Gathering and Warhammer 40K, and finish the user story for Gloomhaven. 

Things to discuss: 
- How to handle matches / infrastructure for legacy games.
- How granular do we want info tracking to be.

**Comment by jiyeongchloe** [comment]
In-Person Meeting Notes:
- we decided to stick with one match per lobby

have updated wiki page to reflect this change.

Task is completed, will close issue.

Nat: talked through ideas
Chloe: documented user stories on wiki page

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Really great user stories! Good mapping of user flow for ending procedures. My only comment is that you are missing a closing statement as the final comment.
