### ISSUE TITLE
(matches) create user stories for match outcome data (Annika)

### ISSUE THREAD

**Issue by ambr-lise** [uchicago-cs/chigame#80]
Goal: We are looking to clarify what match data will be available to a user from their profile, and what match data other users will see when they look at that user's profile.

Deliverables: User stories for different games which return distinct types of data. These stories should show what type of data is stored after the match, how the user who played in the match can interact with this data, and how that user's friends can interact with this data, and how other users on the site can interact with this data.

**Comment by ambr-lise** [comment]
See the wiki entry "Match Outcomes" on the Matches wiki page: https://github.com/uchicago-cs/chigame/wiki/Matches-~-User-Stories.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Really thorough and well-thought out user stories! I love that you have many different examples along with the exact type of victory. How do you plan to store the match statistics? Will you have historical statistics sorted by game? Also, please leave a closing statement when you are finished with the issue next time!
