### ISSUE TITLE
user stories for using the API to get match / tournament information

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#82]
**Goal**: Create user stories for apis that shows what it would look like when a user would GET match and/or tournament information. Ensure we fully encompass what we hope the final product of that would look like.

**Comment by Esterello2** [comment]
Reached out to Tournament team to inquire about Tournament model and format to help with endpoint creation

**Comment by giomhern** [comment]
Hi Esteban! Did you get any updates on the tournament model and how we can formulate the user stories? If not, I can think we can gauge with best interest how it can be possible to use a stub idea of what the tournaments works like / should work like. Let us know!

**Comment by cuyakonwu** [comment]
I just created admin and user stories for GET tournament endpoint

**Comment by cuyakonwu** [comment]
Created admin and user stories for POST games endpoint

**Comment by cuyakonwu** [comment]
# GET Match Endpoint:
As a ChiGame user, Ronald wants to access detailed information about a specific match. When navigating to the "Get Match" endpoint at /api/matches/{match_id}, he expects to receive comprehensive data such as the date and time the match was played, the game being played, the participants, their roles or factions, the turn order, and any specific details related to the game's mechanics.

- The GET endpoint at /api/matches/{match_id} successfully retrieves match information.
- The response includes relevant details such as date and time, game name, participants, roles or factions, turn order, and any other pertinent data related to the specific match.

**Comment by cuyakonwu** [comment]
# POST Match Endpoint:
As a ChiGame user, Ronald wants to record the outcome of a completed match and contribute to the platform's match statistics. When posting match results to the endpoint at /api/matches, he is expected to provide essential details such as the game played, participants, their roles or factions, and the specific outcomes, whether it's a victory, defeat, or any other relevant result. Additionally, he wants the platform to update relevant statistics, such as win/loss records and achievements.

- The POST endpoint at /api/matches successfully records match outcomes.
- The request includes necessary information like game name, participants, roles or factions, and the specific results of the match.
- The platform updates relevant statistics, such as win/loss records and achievements, based on the posted match outcome.
- Users can view the updated match information in their profiles or other relevant sections of the platform.

**Comment by cuyakonwu** [comment]
The implementation for GET/POST match and tournaments has successfully been outlined by the user stories found [here](https://github.com/uchicago-cs/chigame/wiki/API-~-User-Stories). This will allow for future implementations to be mindful of the guidelines created by said use stories, being able to change them as Chigame develops

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Nice work y'all! Thank you for working to communicate over the updates as well as uploading the user stories to the wiki!
