### ISSUE TITLE
Create User Stories for Anonymous Internet Devices (i.e runnable python or bot simulator)

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#83]
**Goal**: Create a user story that shows what the experience for any given internet device requesting information from chigame would be like. This includes creating databases based on users or games played on the website. This also includes bots simulating 100s or 1000s of games that are provided on the website

**Comment by giomhern** [comment]
This is an instance of what a user story can be (be it that I did not misunderstand it) ~ not flushed out completely:

1. Taylor's internet-enabled device sends a request to the Chigame API to retrieve data on games and user interactions.
2. The device receives and stores this information in its local database, categorizing data by game titles and user demographics.
3. The device deploys bots to play hundreds of games on Chigame, generating performance and gameplay data.
4. Taylor uses the collected data for comprehensive analysis to understand user behavior and game popularity, and to identify areas for enhancement.

**Comment by cuyakonwu** [comment]
Yep that sounds like a good instance of anonymous internet users!

**Comment by giomhern** [comment]
@cuyakonwu Since they received your approval, I have just added them into the wiki. They can be found at this [page of the wiki](https://github.com/uchicago-cs/chigame/wiki/API-~-User-Stories). As a result, thank you for review and I will be closing this issue for now.

**Comment by majorsylvie** [comment]
Issue Score: Satisfactory

Comments:
Thank you for uploading these user stories to the wiki!

Few points of feedback:
- this title is not specific to the API teams. It's too generic and could then be confused with other teams. 
- This issue also took 2 sprints to be commpleted
- Then finally, you did not close and specify the developer contributions. I can make some assumptions based on the update log here, but it's better to state who did what!
