### ISSUE TITLE
Create the list view for tournaments

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#86]
In this task, we would like to create a list view for tournaments, on which we will be able to see all the tournaments created. This is a part of the CRUD pages.

**Comment by MikeChen012345** [comment]
For the list view, staff, non-admin users, and guests (not logged in) are all able to see the information related to the tournament. The fields displayed are ("name",  "game", "start_date", "end_date", "max_players", "description", "rules", "draw_rules", "matches", "players", "winners"). The code is on pull request #187

**Comment by MuyanXie** [comment]
Closing Statement:

@MikeChen012345 worked on coding the soluting for the list view together with @MuyanXie . @jb-01 worked on researching the best way to represent a list view for tournaments

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice work on this PR and for fixing all the merge conflicts.
