### ISSUE TITLE
Implement a `Delete` view for tournaments

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#87]
Details:

We will implement the Delete in CRUD for our models in the views.py file, enabling the web server to accept authenticated and authorized users to delete a specific tournament.

Goals:

Upon the conclusion of the issue, we should have a robust views.py file with valid delete methods for the entities with correct relationships mapped between the entities.

Notes:

We should pay attention to give the delete right to only authenticated and authorized users

**Comment by MikeChen012345** [comment]
We have implemented the delete view for the tournaments. Currently, only staff members are allowed to delete a tournament. This would be changed later to allow non-admin users to access the functionalities with restrictions (issue #172 ). The related pull request is #188

**Comment by MuyanXie** [comment]
Closing Statement:

@MikeChen012345 and @jb-01 worked on coding the classes and functions for delete view. @MuyanXie worked on reviewing the structure of the code as well as checking everything is under the right track for CRUD pages

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Same comment as to the other CRUD related PRs. Good work on splitting it up and fixing merge issues between the team.
