### ISSUE TITLE
Create a create view for tournaments

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#88]
In this issue, we will create a create view for the tournaments. This page allows users (restrictions may apply, but are not determined currently) to create a new tournament and specify certain properties of the tournament (e.g., number of participants, tournament type, rewards, etc.).

**Comment by MikeChen012345** [comment]
On the create view, users are able to create a tournament and assign values to most of the attributes (the link to the create view is located on the list view and only appears when the user is a staff member). Currently, we only allow staff to create tournaments, which may be changed later with restrictions. The code is on pull request #187

**Comment by MuyanXie** [comment]
Closing Statement:

@MikeChen012345 and @jb-01 worked on coding the classes and functions for create view. @MuyanXie worked on reviewing the structure of the code as well as checking everything is under the right track for CRUD pages

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work explaining exactly what this view is for in the update!
