### ISSUE TITLE
Reach out to users team to ask them about their search bar and see what we need to consolidate

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#89]
We will be coordinating with the users team to discuss potentially making a consolidated search bar that works for searching both games and user accounts.

**Comment by frowenz** [comment]
We've been coordinating with the user team to determine the best approach for a unified search feature.

@omarelkashef from the user team highlighted two main methods for implementing search and filtering:

1. Allowing users to filter results while searching, akin to the functionality on [Rate Your Music](https://rateyourmusic.com/) and [Board Game Geek](https://boardgamegeek.com/).
2. Providing the option to search first and then apply filters, similar to what is done on [Goodreads](https://www.goodreads.com/) and [Letterboxd](https://letterboxd.com/).

During our discussions, we found the Board Game Geek's search implementation to be particularly streamlined. We also considered whether to include tournament data in the search results and think it may be beneficial to consult with the tournaments team on this matter.

**Comment by frowenz** [comment]
We have met with the user team and have decided to create two two issues that members from both teams will work on. 

Issues: 
1. Create a search bar with the ability to specify whether users or games are being queried.
2. Create a search landing page to display either users or games. 

Once, these issues are created, they will be linked and this issue will be closed.

**Comment by omarelkashef** [comment]
During the sprint review meeting on 11/06/23, @elizabethli31 mentioned that the matches team also discussed the need for a search bar, so we need to make sure our implementation fits their use as well.

**Comment by frowenz** [comment]
> During the sprint review meeting on 11/06/23, @elizabethli31 mentioned that the matches team also discussed the need for a search bar, so we need to make sure our implementation fits their use as well.

My instinct is that a general search for users or games would be separate from a match search. @nugerhard do you have any thoughts?

**Comment by nugerhard** [comment]
@frowenz: this makes sense to me. I think we were imagining the lobby search as a filtering tool on an existing list of lobbies vs. an aggregating tool in its own right. While we could add lobbies as reachable by this "consolidated platform search", I feel like that type of search is better reserved for more static entities like users, games, groups, etc. 

I'd also note that Board Game Arena lobbies/tables don't seem searchable from the main search bar, which is another point for this design choice.

**Comment by omarelkashef** [comment]
@nugerhard that is probably the best approach. In that case, we just keep the search bar for users and games

**Comment by frowenz** [comment]
Closing this issue. 

We reached out to the user and tournament teams and came up with the following plan:

The general search bar will be for users and games only. ChiGame Users will decide whether they are searching for users or games as they search. A first pass has been implemented in #176. The current strategy involves a shared search results page, with distinct handling of search views and URLs.

The main remaining tasks are to add autocomplete (#95) and to add search and filtering capabilities on the results page (#191). A smaller remaining task (no issue yet) is to improve the UI.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
The only thing this issue is missing is a goal in the summary. Something like "reach out to the users team to decide if/how our search bar will integrate users and games".

Great work communicating and updating the issue with information from discussions and meetings! 

Great work outlining and then linking relevant issues as well. 

This is a phenomenal example of an communication and design-focused issue.
