### ISSUE TITLE
Research how to add autocomplete to a search bar

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#94]
This task will involve research on how to add autocompletion/dropdown to our search bar's functionality (to be created in issue #93 ). We need to research how to add autocomplete to a text input field and how to have the autocomplete options show up and be clickable by users to select that option.

**Comment by ptlin25** [comment]
This is also mentioned in #91. The website GeeksForGeeks provided a good [example](https://www.geeksforgeeks.org/implement-search-autocomplete-for-input-fields-in-django/) of a text input field that uses a jQuery UI widget (for more information see [documentation](https://jqueryui.com/autocomplete/)) to have autocomplete the input field. The autocomplete is not case sensitive and checks if the text string occurs in any of the options (i.e. the autocomplete option does not have to start with the input string). We can set the options that the input can autocomplete to using the source field. We can pass the list of game names as the autocomplete options.

**Comment by ptlin25** [comment]
Research for how to add autocompletion to a text input field in a form  (that can be used as a search bar) has been completed, so this issue is completed.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job! This is a great example of a small research oriented task that gets documented and closed. 

Thank you for referencing other issues (both relevant for information found, as well as for further progression in the topic of getting a cool search bar working).

Good work and keep going!
