### ISSUE TITLE
Update the game creation page to autofill using the BGG api

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#97]
When a staff member is adding a game through the game create page, they can use a search bar to search for games in BGG and select a game. The game creation page is then autofilled with the details of the specific game supplied by the BGG API. 

See #45 for documentation on using BGG API and some thoughts on how to use it. See #46 for a demo page that uses the BGG API to search and display contents of the result.

**Comment by willcravitz** [comment]
First we will need to finalize #92 so that we know exactly what game information needs to be autofilled by the BGG API.

**Comment by frowenz** [comment]
I have a first pass of this working. This task is dependent on completing #192

https://github.com/uchicago-cs/chigame/assets/69015620/d09db827-32b9-4776-ad70-a079dc55d517

**Comment by frowenz** [comment]
Branch has been added. Currently, it does not include a way to autofill categories or mechanics.

**Comment by frowenz** [comment]
### Closing Comments From Corresponding PR:

This PR introduces a feature for auto-filling game details in the game creation process. Now, users can look up games on Board Game Geek (API) by name. The search results are displayed as a list, and selecting a game from this list automatically fills in the game creation form with data from the BGG API.

#### Relevant Documentation
- General information on the BoardGameGeek API integration: [BoardGameGeek API Documentation](https://github.com/uchicago-cs/chigame/wiki/Games-~-BoardGameGeek-(BGG)-API)
- Creating fixtures using the BoardGameGeek API: [Fixture Creation Documentation](https://github.com/uchicago-cs/chigame/wiki/Games-~-Creating-Fixtures-Using-BoardGameGeek-API)

#### Current Limitations
- XML character parsing issues (this has been solved in [PR #287](https://github.com/uchicago-cs/chigame/pull/287))
- Auto-filling of categories and mechanics is not yet functional.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
As said on the related PR, this is phenomenally well done issue.

Thank you all for your work!
