### ISSUE TITLE
Write up fixture files for games models that have the updated attributes

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#98]
During the first sprint we were all testing the crud pages with random data we had created in our local databases. Now we want to create a set of game fixtures so that we can test on the same data and have controlled results.

Our initial goal is to create 3 fixtures:

1. A "small" fixture of about 5 games. This will be used for quick visual checks on crud and display pages.
2. A "medium" fixture of about 50 games. This will be used for visual checks that involve pagination, sort, etc.
3. A "large" fixture of about 500 games. This will be used to test search, sort, filter, and the efficiency of these operations.

**Comment by majorsylvie** [comment]
waiting on issue #92

**Comment by willcravitz** [comment]
Created branch `game-management/fixtures` to add fixture files.

**Comment by ptlin25** [comment]
Have any of the fixture files been created yet? Which one should I work on?

**Comment by frowenz** [comment]
If we complete #97, it much easier to generate fixtures en masse, especially for the 50 fixtures task and the 500 fixture task.

The 5 fixture task is doable by hand.

**Comment by willcravitz** [comment]
Started work on the 5 fixture task, will push soon.

**Comment by willcravitz** [comment]
5 fixture task completed and pushed to `game-management/fixtures`. Note that some fields were populated by generative AI and others I did by hand so not all information is accurate to BGG. Made a temporary update to game detail template to check that fixture works as expected:
<img width="400" alt="image" src="https://github.com/uchicago-cs/chigame/assets/93291811/7d92672c-5088-4f4a-870d-4834c1f9259e">

**Comment by willcravitz** [comment]
A few other notes:
1. I put the 5 fixture file `games-fixture-small.json` in a new `fixtures` directory in `src`. To run the server with the fixture you need to run `python3 manage.py testserver src/fixtures/games-fixture-small.json` from the root of the repo. Is there a better place to put the fixture files? Will other teams add them here?
2. For our models, `category` is a many-to-many field of games, so I think we should rename it to `categories` the same way we named `mechanics`. Could be worth fixing quickly in #178 before it gets merged in (PR #179)

**Comment by frowenz** [comment]
The code from this pull request can be used to automate the mass creation of fixtures https://github.com/uchicago-cs/chigame/pull/196

**Comment by willcravitz** [comment]
PR #231 added to just merge in the 5 game fixture.

**Comment by willcravitz** [comment]
I wrote the following script the autogenerate fixtures for the top 50 hottest bgg games:
```
import requests
import json
import xml.etree.ElementTree as ET

def fixture_dict_from_bgg_id(pk, id):
  game_url = f"https://www.boardgamegeek.com/xmlapi2/thing?id={id}&stats=1"
  game_response = requests.get(game_url)
  game = ET.fromstring(game_response.text)
  fields = {}
  fields["name"] = game.find(".//name").get("value")
  fields["description"] = game.find(".//description").text
  fields["year_published"] = game.find(".//yearpublished").get("value")
  fields["image"] = game.find(".//image").text
  fields["rules"] = game.find(".//description").text
  fields["min_players"] = game.find(".//minplayers").get("value")
  fields["max_players"] = game.find(".//maxplayers").get("value")
  fields["suggested_age"] = game.find(".//minage").get("value")
  fields["expected_playtime"] = game.find(".//playingtime").get("value")
  fields["min_playtime"] = game.find(".//minplaytime").get("value")
  fields["max_playtime"] = game.find(".//maxplaytime").get("value")
  fields["complexity"] = round(float(game.find(".//averageweight").get("value")), 2)
  fields["BGG_id"] = id
  fields["category"] = []
  fields["mechanics"] = []
  fixture = {"model": "games.game", 
             "pk": pk,
             "fields": fields}
  return fixture

hot_games_url = "https://www.boardgamegeek.com/xmlapi2/hot?boardgame"
hot_games_response = requests.get(hot_games_url)
hot_games = ET.fromstring(hot_games_response.text)

fixtures = []
pk = 1
for game in hot_games:
  game_fixture = fixture_dict_from_bgg_id(pk, game.get("id"))
  fixtures.append(game_fixture)
  pk += 1
json_fixtures = json.dumps(fixtures, indent=4)

with open("games-fixture-hot-50.json", "w") as outfile:
    outfile.write(json_fixtures)
```

And here's the output (waiting to push to the branch until the 5 game fixture has been merged):
[games-fixture-hot-50.json](https://github.com/uchicago-cs/chigame/files/13385054/games-fixture-hot-50.json)

A few notes on the output fixture:

- I set description and rules to be the same because there's a lot of overlap. I think we're going to need a "short description" down the line because a lot of the BGG ones are really long and could break the UI.
- I'm not sure if BGG provides an expected playtime, because the "playingtime" attribute always seems to be the max playtime
- I didn't add categories and mechanics, but this information is included in the BGG api call
- I didn't include publishers and people

**Comment by frowenz** [comment]
@willcravitz Given a long description, it is easy to to cut it off down on the frontend. Nice observation about the playingtime also being the same about maxplaytime. Perhaps we should remove expected playtime.

**Comment by frowenz** [comment]
I modified your script to using batching which avoids getting rate limited. Also, I added the ability to get any number of games.

```python
import requests
import xml.etree.ElementTree as ET
import json


def bgg_get_game_details(bgg_ids):
    BGG_BASE_URL = "https://www.boardgamegeek.com/xmlapi2/"
    ids_string = ",".join(map(str, bgg_ids))
    details_url = f"{BGG_BASE_URL}thing?id={ids_string}&stats=1"
    details_response = requests.get(details_url)
    details_root = ET.fromstring(details_response.text)

    games_data = []
    for item in details_root.findall("item"):
        # Extract game details as before, but for each item
        name_element = item.find(".//name[@type='primary']")
        if name_element is None:
            continue  # Skip games without a name

        # Retrieve the complexity value from the API response, convert it to a float,
        # and round it to two decimal places. If the value is not found, default to None.
        if item.find(".//averageweight") is not None:
            complexity_value = item.find(".//averageweight").get("value")
            rounded_complexity = (
                round(float(complexity_value), 2) if complexity_value else None
            )
        else:
            rounded_complexity = None

        # Construct a dictionary with the game's details, parsing various elements from the API response
        game_data = {
            "BGG_id": item.get("id"),
            "name": item.find(".//name").get("value"),
            "image": item.find(".//image").text
            if item.find(".//image") is not None
            else "/static/images/no_picture_available.png",
            "description": item.find(".//description").text,
            "year_published": int(item.find(".//yearpublished").get("value"))
            if item.find(".//yearpublished") is not None
            else None,
            "min_players": item.find(".//minplayers").get("value"),
            "max_players": item.find(".//maxplayers").get("value"),
            "expected_playtime": item.find(".//playingtime").get("value"),
            "min_playtime": item.find(".//minplaytime").get("value"),
            "max_playtime": item.find(".//maxplaytime").get("value"),
            "suggested_age": item.find(".//minage").get("value"),
            "complexity": rounded_complexity,  # The rounded complexity rating of the game
            # Missing fields: category, mechanics
        }

        games_data.append(game_data)

    return games_data


def create_fixture_file(num_entries, filename="fixture_file.json", batch_size=10):
    fixtures = []
    fetched_games = 0
    bgg_id = 1

    while fetched_games < num_entries:
        batch_ids = list(range(bgg_id, bgg_id + batch_size))
        games_data = bgg_get_game_details(batch_ids)

        for game_data in games_data:
            if fetched_games >= num_entries:
                break

            fixture_entry = {
                "model": "games.game",
                "pk": fetched_games + 1,
                "fields": {
                    "name": game_data.get("name", ""),
                    "description": game_data.get("description", ""),
                    "year_published": game_data.get("year_published", None),
                    "image": game_data.get("image", ""),
                    "rules": "",
                    "min_players": game_data.get("min_players", ""),
                    "max_players": game_data.get("max_players", ""),
                    "suggested_age": game_data.get("suggested_age", ""),
                    "expected_playtime": game_data.get("expected_playtime", ""),
                    "min_playtime": game_data.get("min_playtime", ""),
                    "max_playtime": game_data.get("max_playtime", ""),
                    "complexity": game_data.get("complexity", None),
                    "BGG_id": game_data.get("BGG_id", ""),
                    "category": [], 
                    "mechanics": [], 
                },
            }

            fixtures.append(fixture_entry)
            fetched_games += 1
            print(f"Added game {fetched_games} of {num_entries}")

        bgg_id += batch_size

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(fixtures, f, ensure_ascii=False, indent=4)


# Example usage
create_fixture_file(500)  # This will create a fixture file with 10 entries
```

[games-fixtures-500.json](https://github.com/uchicago-cs/chigame/files/13385772/games-fixtures-500.json)

**Comment by frowenz** [comment]
I also discovered a funny edge case. [Go](https://boardgamegeek.com/xmlapi2/thing?stats=1&id=188) has a year published of `-2200`. Hence, we have to update the attribute as follows:
```python
year_published = models.PositiveIntegerField(null=True, blank=True)
                              ↓
year_published = models.IntegerField(null=True, blank=True)
```

**Comment by willcravitz** [comment]
Closing comments: 
As we set out to do, this issue resulted in the creation of 3 fixtures: `games-fixture-5.json` with 5 games,  `games-fixture-50.json` with 50 games, `games-fixture-500.json` with 500 games. The 5 game fixture was written by hand, and the 50 and 500 game fixtures were generated by a script which takes BGG ids and outputs json models of the games using the BGG api. These fixtures were added over two PRs: #231 and #246.

Developer contributions:
@willcravitz wrote the 5 game fixture and helped develop the script to generate fixtures using the BGG api.
@frowenz developed the script the generate fixtures from BGG api, used it to create the 50 and 500 game fixtures, and made some updates to the game model.
@ptlin25 provided feedback and tested.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Phenomenal work!! The back and forth on this larger than anticipated issue is admirable and very much appreciated.

@frowenz @willcravitz thank you incredibly for your work in developing the script, documentation, and fixtures!

Great work discussing changes and evolving problems (such as go and needing to wait for scripts and PR's to be finished.

Be proud of your work y'all!
